### ISSUE TITLE
distribute logic with NodePort? 

### ISSUE THREAD

**Issue by TiloGit** [kubernetes-sigs/aws-alb-ingress-controller#1012]
what is the logic to distribute traffic? 

I use, target-type "default" so **instance**, my service is "**NodePort**" and have 2 replicas (so 2pods) 
When I hit the ALB with curl request from 4 different IPs but always get to same pod. (ping page show host name)
When I force delete a pod I instantly get to other pod. 

ALB monitor show up to 75request, is that to less to see LB occur? 

here my config: 
```yaml
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    #alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/scheme: internet-facing
```

Thanks
Tilo
