### ISSUE TITLE
IAM Role for alb-ingress-controller service account issue discovering aws-vpc-id

### ISSUE THREAD

**Issue by marcincuber** [kubernetes-sigs/aws-alb-ingress-controller#1031]
I am running latest version of alb-ingress-controller which supports IAM roles for service accounts.

My cluster is setup so that I am restricting access to Amazon EC2 Instance Profile Credentials using the following (commands block ALL containers from using the instance profile credentials):
```
yum install -y iptables-services
iptables --insert FORWARD 1 --in-interface eni+ --destination 169.254.169.254/32 --jump DROP
iptables-save | tee /etc/sysconfig/iptables 
systemctl enable --now iptables
```

So, I restricted access to instance profile credentials and deployed alb-ingress-controller with the following service account resource:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::012345678:role/ceng-eks-staging-alb-ingress-controller
```

My alb deployment is discovering both `--aws-vpc-id` and `--aws-region` variables. With the restricted access it is unable to fetch those values. So, my questions are:
Is it possible to use IAM role attached to service account to discover the above variables? Or do I still need to use something like kube2iam just to access ec2metadata?

Thanks
