### ISSUE TITLE
High amount of leader election call's for AdmissionReview 

### ISSUE THREAD

**Issue by vincentheet** [kubernetes-sigs/aws-alb-ingress-controller#1040]
We are experiencing a high amount of leader election calls originating from the alb-ingress-controller. We see this behaviour in our custom ValidatingWebhookConfiguration  / AdmissionController which receives UPDATE/CREATE/DELETE/e.g. actions for all resources. As we specified in a ValidatingWebhookConfiguration. 

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-modules-eks-admission-controller
webhooks:
  - name: "admission-controller.domain.tld"
    failurePolicy: Ignore
    rules:
      - operations:
          - "*"
        apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - "*"
    clientConfig:
      url: ""
```

After we added the AdmissionControl we saw a huge number of call's coming in. We investigated this and eventually we saw that about 99% of them where coming from the leader election ConfigMap that is used by the aws-alb-ingress-controller. Here is an example of such a call.

```json
{
    "kind": "AdmissionReview",
    "apiVersion": "admission.k8s.io/v1beta1",
    "request": {
        "uid": "dcf3d808-e04a-11e9-bb90-0ab3a2405b02",
        "kind": {
            "group": "",
            "version": "v1",
            "kind": "ConfigMap"
        },
        "resource": {
            "group": "",
            "version": "v1",
            "resource": "configmaps"
        },
        "name": "ingress-controller-leader-alb",
        "namespace": "kube-system",
        "operation": "UPDATE",
        "userInfo": {
            "username": "system:serviceaccount:kube-system:alb-ingress",
            "uid": "6aef88fd-cfe2-11e9-aadb-0291aefcd5ae",
            "groups": [
                "system:serviceaccounts",
                "system:serviceaccounts:kube-system",
                "system:authenticated"
            ]
        },
        "object": {
            "kind": "ConfigMap",
            "apiVersion": "v1",
            "metadata": {
                "name": "ingress-controller-leader-alb",
                "namespace": "kube-system",
                "selfLink": "/api/v1/namespaces/kube-system/configmaps/ingress-controller-leader-alb",
                "uid": "8267e57b-cfe2-11e9-bb90-0ab3a2405b02",
                "resourceVersion": "3474868",
                "creationTimestamp": "2019-09-05T13:38:56Z",
                "annotations": {
                    "control-plane.alpha.kubernetes.io/leader": "{\\"holderIdentity\\":\\"alb-ingress-controller-5bc4d5ff74-9rrg5_f1d2ddd4-e033-11e9-a64f-3abdd1b7e0dd\\",\\"leaseDurationSeconds\\":15,\\"acquireTime\\":\\"2019-09-26T08: 02: 30Z\\",\\"renewTime\\":\\"2019-09-26T10: 46: 15Z\\",\\"leaderTransitions\\":38}"
                }
            }
        },
        "oldObject": {
            "kind": "ConfigMap",
            "apiVersion": "v1",
            "metadata": {
                "name": "ingress-controller-leader-alb",
                "namespace": "kube-system",
                "uid": "8267e57b-cfe2-11e9-bb90-0ab3a2405b02",
                "resourceVersion": "3474868",
                "creationTimestamp": "2019-09-05T13:38:56Z",
                "annotations": {
                    "control-plane.alpha.kubernetes.io/leader": "{\\"holderIdentity\\":\\"alb-ingress-controller-5bc4d5ff74-9rrg5_f1d2ddd4-e033-11e9-a64f-3abdd1b7e0dd\\",\\"leaseDurationSeconds\\":15,\\"acquireTime\\":\\"2019-09-26T08: 02: 30Z\\",\\"renewTime\\":\\"2019-09-26T10: 46: 13Z\\",\\"leaderTransitions\\":38}"
                }
            }
        },
        "dryRun": false
    }
}
```

These calls are happening every 2 seconds which is in my opinion more than needed and it also conflicts with the 15 seconds stated in the call under the leaseDurationSeconds property.

I tried to dig in the code and find the cause but unfortunately I was unsuccessful.
