### ISSUE TITLE
Multiple paths on rule

### ISSUE THREAD

**Issue by brunomanzo** [kubernetes-sigs/aws-alb-ingress-controller#1046]
When I add a rule in a ALB listener it is possible to add multiple path conditions, like:
/path1 or /path2.

How can I achieve that by ingress file?

**Comment by catalinmer** [comment]
Hi, I'm also interested in this. Have you found a way to do this other than multiple rules with same backend?

**Comment by tomfotherby** [comment]
I couldn't get this working either.

I tried:

```
      - path:
        - /test1
        - /test2
        backend:
          serviceName: foo
          servicePort: 80
```

but the `kubectl apply` gave:

> error: error validating "foo-alb-ingress.yaml": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[2].path): invalid type for io.k8s.api.networking.v1beta1.HTTPIngressPath.path: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

and I tried: 

```
      - path: /test1, /test2
        backend:
          serviceName: foo
          servicePort: 80
```

but the controller logs gave:

> default/foo-alb-ingress: failed modifying rule 2 on arn:aws:elasticloadbalancing:us-east-1:redacted:listener/app/redacted:listener-default-fooalbing-redacted:listener due to ValidationError: Condition value '/test1, /test2' contains a character that is not valid
