### ISSUE TITLE
EKS: failed to reconcile targetGroups due to failed to load serviceAnnotation due to no object matching key

### ISSUE THREAD

**Issue by masterkain** [kubernetes-sigs/aws-alb-ingress-controller#1053]
I'm trying to setup nginx-ingress and aws-alb-ingress-controller on a EKS/eksctl/flux cluster, so I deploy some helm charts though helm operator.

my public subnets are tagged correctly, although I see in some image from official doc that there's a label called role/alb, not sure what that is that but it's not applied.
![Screenshot 2019-10-24 at 14 09 46](https://user-images.githubusercontent.com/12844/67484256-fab8f300-f667-11e9-94d7-b03bf17ea529.png)

I have no idea how to solve the issue.

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aws-alb-ingress-controller
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: aws-alb-ingress-controller
  chart:
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    name: aws-alb-ingress-controller
    version: 0.1.11
  values:
    clusterName: bsmart
    autoDiscoverAwsVpcID: true
    autoDiscoverAwsRegion: true
```

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "bsmartalb"
  labels:
    app: "bSmartALBApp"
  annotations:
    fluxcd.io/ignore: "false"
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: "instance"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200,404"

spec:
  # forward all requests to nginx-ingress-controller
  rules:
  - http:
      paths:
      - path: "/*"
        backend:
          serviceName: "nginx-ingress-controller"
          servicePort: 80
```

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.24.3
  values:
    controller:
      service:
        type: NodePort # disable ELB
        externalTrafficPolicy: Local # If controller.service.type is NodePort or LoadBalancer, set this to Local to enable source IP preservation
        # controller.service.healthCheckNodePort: https://github.com/helm/charts/tree/master/stable/nginx-ingress
      metrics:
        enabled: false
    defaultBackend:
      service:
        type: NodePort # to configure the default HTTP back-end as a NodePort to make it visible to the ALB Ingress.
```

the error:

```
2019-10-24T12:02:11.235300758Z E1024 12:02:11.235152       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile targetGroups due to failed to load serviceAnnotation due to no object matching key \"default/nginx-ingress-controller\" in local store"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"bsmartalb"}
```
