### ISSUE TITLE
Error using Cognito

### ISSUE THREAD

**Issue by jpmolinamatute** [kubernetes-sigs/aws-alb-ingress-controller#1054]
Hello!

I'm configuring an ingress to support Cognito authentication but so far without success :-(
I'm getting an error, but the error message is not descriptive enough to fully understand what's going on.

This is the annotation that I'm using

```
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:XXXXXXXXXXX:certificate/ZZZZZZ-ZZZZ-ZZZZ-ZZZZ-ZZZZZZZZZZZZZZZZZZZ
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    alb.ingress.kubernetes.io/auth-scope: "email profile openid"
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:us-east-2:XXXXXXXXXXX:userpool/us-east-2_123456", "UserPoolClientId":"YYYYYYYYYYYYYYYYYYY", "UserPoolDomain":"auth"}'
```

and this is the error message that I'm getting

`E1024 13:39:04.835393       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile listener due to InvalidLoadBalancerAction: The user pool client must have a client secret\n\tstatus code: 400, request id: 9af062f1-dc34-44b2-9c35-4136a1bd88b4"  "controller"="alb-ingress-controller" "request"={"Namespace":"bigdata","Name":"nginx"}`

what would be the best way/approach to debug further or fix this problem???

thanks for your time! :-)
