### ISSUE TITLE
different healthcheck PATH for different target group

### ISSUE THREAD

**Issue by saravana-code** [kubernetes-sigs/aws-alb-ingress-controller#1056]
I am running multiple pods , node app, java app on k8s and using ALB ingress controller with different paths, but I have different healthcheck urls like /health for TG1, /actuator for TG2, /status for TG3.

I have tried using this annotation alb.ingress.kubernetes.io/healthcheck-path: /ping    but this add /ping to all the TGs, how can i pass different healthcheck-path for different target group, pls advice

**Comment by Eraac** [comment]
You should set the annotation at the Service Object level, not Ingress Object

**Comment by saravanakumarangamuthu** [comment]
@Eraac  thanks for the response, can you give me more info please? you mean the service.yml needs to be defined with healthchecks instead of ingress ?

**Comment by Eraac** [comment]
Absolutely, instead of set the annotation into kind Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ...
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    ...
```

You can set health check into the kind Service, in the same way
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    ...
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    ...
```
