### ISSUE TITLE
Incomprehensible error message...

### ISSUE THREAD

**Issue by rojopolis** [kubernetes-sigs/aws-alb-ingress-controller#1069]
Can anyone help me parse this error:
`failed to reconcile targetGroups due to failed to reconcile targetGroup targets due to Unable to find server port on service argo-cd-argocd-server`

There is a targetPort defined with the name `server`, but other than that I'm at a loss as to what the problem could be:
```yaml
ports:
        - name: server
          containerPort: 8080
          protocol: TCP
```
Thanks for any help.
