### ISSUE TITLE
hostNetwork can not use a port either than 80 

### ISSUE THREAD

**Issue by laopojiaotutu** [kubernetes-sigs/aws-alb-ingress-controller#1083]
I use the hostnetwork , merge the default values.yaml of helm repo with belows:
```
controller:
  kind: DaemonSet
  containerPort:
    http: 180
    https: 1443
  hostNetwork: true
  daemonset:
    useHostPort: true
    hostPorts:
      http: 180
      https: 1443
  service:
    ports:
      http: 180
      https: 1443
defaultBackend:
  image:
    repository: mirrorgooglecontainers/defaultbackend-amd64
  port: 18080
  service:
    servicePort: 180
```
but the pod log show the 80 port still not changed :

```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       0.26.1
  Build:         git-2de5a893a
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: openresty/1.15.8.2

-------------------------------------------------------------------------------

I1128 08:15:45.766027       6 flags.go:198] Watching for Ingress class: nginx
F1128 08:15:45.767753       6 main.go:64] port 80 is already in use. Please check the flag --http-port
```
