### ISSUE TITLE
Monitoring ALB Target Groups

### ISSUE THREAD

**Issue by dudicoco** [kubernetes-sigs/aws-alb-ingress-controller#1086]
I'm not sure if this falls under a feature request.
When an ALB is created/modified by the controller the target groups which are defined in the rule could have unhealthy hosts even though the service is working properly within K8S.

Setting up cloudwatch alerts is difficult since the ALB creation/modification is dynamially triggered by the controller.
Is there a way to automatically set up alerts for the target groups via cloudwatch?

**Comment by s2504s** [comment]
So, creating new TargetGroup is new API call from ALB ingress controller. You can process this Event using CloudWatch Events https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/EventTypes.html
You can invoke some lambda when event happens using Events option "Select Target to invoke when an event matches your Event Pattern or when schedule is triggered"

**Comment by dudicoco** [comment]
Thanks @s2504s, I've already implemented the exact same solution, however, I would prefer for the controller to do this.

**Comment by s2504s** [comment]
@dudicoco 
Hmmm... I think this ability is out of scope of tasks for ALB Ingress controller

**Comment by leoskyrocker** [comment]
We use terraform to create and manage cloudwatch alerts.

aws-alb-ingress-controller is already one new tool that also comes in and touches our infrastructure, and we would not prefer to have a third way that creates and manages our infra such as a cloudwatch event triggered lambda that creates a new Cloudwatch Alert.

My point is there are use cases and companies where operators would like to have a single source of truth or single place of management for all infrastructure, and, unfortunately, I think aws-alb-ingress-controller isn't really being supportive of this spirit at this moment.

**Comment by leoskyrocker** [comment]
I think this is closely related to https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1116

**Comment by seivan** [comment]
@leoskyrocker Exactly! Put it perfectly btw, I haven't been able to express how poorly this fits in with Terraform/Pulumi setups for infra, you nailed it. 

Setting up a lambda as suggested earlier to get the name is just plain ridiculous and claiming it's "out of scope" to get a *predictable* name that can be used for various reasons, Cloud watch being one of them, is crazy, how can a config param for the ALB be out of scope?! 

The issue is the way `aws-alb-ingress-controller` is setup currently cause frictions with tools made for setting up infrastructure as this problem doesn't exist with anything in our stack (Databases, VPC, CDN, S3, etc).

**Comment by dudicoco** [comment]
I was able to create alerts via Prometheus by using a CloudWatch exporter to import the metrics:  https://github.com/ivx/yet-another-cloudwatch-exporter

Configuration file:
```
discovery:
  exportedTagsOnMetrics:
    alb:
    - kubernetes.io/ingress-name
    - kubernetes.io/service-name
    - kubernetes.io/namespace
  jobs:
  - type: alb
    regions:
    - {{ .vars.region }}
    searchTags:
    - Key: ingress.k8s.aws/cluster
      Value: {{ .vars.clusterName }}
    delay: 120
    length: 600
    metrics:
    # Load Balancer
    - name: HTTPCode_ELB_4XX_Count
      statistics:
      - Sum
      period: 60
      nilToZero: true
    - name: HTTPCode_ELB_5XX_Count
      statistics:
      - Sum
      period: 60
      nilToZero: true
    - name: RequestCount
      statistics:
      - Sum
      period: 60
      nilToZero: true
    # Target Group
    - name: HTTPCode_Target_4XX_Count
      statistics:
      - Sum
      period: 60
      nilToZero: true
    - name: HTTPCode_Target_5XX_Count
      statistics:
      - Sum
      period: 60
      nilToZero: true
    - name: TargetConnectionErrorCount
      statistics:
      - Sum
      period: 60
      nilToZero: true
    - name: TargetResponseTime
      statistics:
      - Average
      period: 60
    - name: UnHealthyHostCount
      statistics:
      - Maximum
      period: 60
```

Prometheus alert example:
```
- alert: UnhealthyHostInTargetGroup
  annotations:
    summary: Unhealthy host detected in target group {{ $labels.dimension_TargetGroup }} of load balancer {{ $labels.dimension_LoadBalancer }}
    identifier: '{{ $labels.tag_kubernetes_io_namespace }}/{{ $labels.tag_kubernetes_io_ingress_name }}/{{ $labels.tag_kubernetes_io_service_name }}'
  expr: |
    sum(aws_alb_tg_un_healthy_host_count_maximum{tag_kubernetes_io_ingress_name="my-ingress",tag_kubernetes_io_service_name="my-service"}) > 0
  for: 1m
  labels:
    severity: critical
```
