### ISSUE TITLE
Load balancer assigns private subnet incurring in timeouts (EKS)

### ISSUE THREAD

**Issue by paltaa** [kubernetes-sigs/aws-alb-ingress-controller#1098]
this is my ingress.yaml file, also we are using external DNS for route53

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
    # Redirect for requests to 443
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # Stickyness related annotations
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=600
    #   Certificate arn from Amazon AC. Can be a list
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:******
  name: foris-ingress
spec:
  tls:
    - hosts:
        - "*****"
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
    - host: ****
      http:
        paths:
          - path: /*
            backend:
              serviceName: darwined-nodeport
              servicePort: 80

```

This is a staging environment for qa, but when making the requests with postman it sometimes, randomly timeouts, by curling could get this:

```
curl -k  -v     ****
*   Trying ****...
* connect to **** port 443 failed: Connection timed out
*   Trying ***...
* Connected to *** (***) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 597 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification SKIPPED
* 	 server certificate status verification SKIPPED
* 	 common name: *.hyades.foris.ai (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=*.hyades.foris.ai
* 	 start date: Fri, 22 Nov 2019 00:00:00 GMT
* 	 expire date: Tue, 22 Dec 2020 12:00:00 GMT
* 	 issuer: C=US,O=Amazon,OU=Server CA 1B,CN=Amazon
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
```

Okay, now I've been doing `nslookups` and found there are 3 servers, one of them is giving the timeout, so the created application load balancer is assigning 2 public subnets and 1 private subnet that is generating this error, any thoughts on why this is happening?
