### ISSUE TITLE
Is it possible to have only 1 ALB instead 4(for every ingress)

### ISSUE THREAD

**Issue by vrathore18** [kubernetes-sigs/aws-alb-ingress-controller#1107]
I am using aws-alb-ingress-controller in my k8s setup. I am have 4 services which need loadbalancer. Currently I am have 4 different ingress and it is creating 4 alb, which is not good as per cost efficiency.

my current  ingress sample:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "pd.graphql.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingressScheme }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.external.acmCertificateARN }}
    alb.ingress.kubernetes.io/healthcheck-path: /liveness
    alb.ingress.kubernetes.io/inbound-cidrs: {{ .Values.ipWhiteList }}
spec:
  rules:
    - host: b.{{ .Values.domainName }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ template "pd.graphql.fullname" . }}
              servicePort: 80
```

**Comment by naorlivne** [comment]
You need to create a single ingress which contains multiple hosts, for example:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress"
  namespace: "2048-game"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: 2048-ingress
spec:
  rules:
    - host: host1.example.com
      http:
         paths:
            - path: /*
              backend:
                serviceName: "service-2048"
                servicePort: 80
    - host: host2.example.com
      http:
         paths:
            - path: /*
              backend:
                serviceName: "service-20482"
                servicePort: 80
```
