### ISSUE TITLE
Default action for a listener

### ISSUE THREAD

**Issue by s2504s** [kubernetes-sigs/aws-alb-ingress-controller#1110]
Is it possible  to add an annotation for ingress for defining a default rule for a listener?
It is possible for configuring ALB from AWS Console, so ingress should have the same ability, I think.
(I am using alb ingress controller v1.2)

**Comment by s2504s** [comment]
Yes. It is possible if we use this annotation
`https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#actions`

**Comment by iBavtovich** [comment]
@s2504s Hi. 
Can you please elaborate on how you implemented default action for ALB listener?

**Comment by s2504s** [comment]
@iBavtovich 
Have you tried to use annotations, as I mentioned above?

**Comment by iBavtovich** [comment]
Sure, I only can do some kind of workaround: create specific action (as example with 401 response) and place it as the last one action in the sequence. But it is not the default one. Default one - send 404 response.

**Comment by jithendra89** [comment]
Can you please give a sample? 
`apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: qbxekscluster-alb2-ingress-group
    alb.ingress.kubernetes.io/actions.default: >
      {"Type":"fixed-response","FixedResponseConfig":{"ContentType":"text/plain","StatusCode":"503","MessageBody":"503 error text"}}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: default
              servicePort: use-annotation`

I tried this and it is not working

**Comment by jreading** [comment]
Correct me if I'm wrong @jithendra89 but you are looking to see the listeners on the ALB resource itself and not just handled in the controller?

**Comment by TjeuKayim** [comment]
This configuration works for me:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.default: '{"fixedResponseConfig":{"contentType":"text/html","messageBody":"Hi","statusCode":"200"},"type":"fixed-response"}'
    kubernetes.io/ingress.class: alb
  name: api
spec:
  backend:
    # These lines are important!
    serviceName: default
    servicePort: use-annotation
  rules:
  - http:
      paths:
        # ...
  tls:
  - hosts:
    # ...
```
