### ISSUE TITLE
How to debug the network activity (ALB Ingress too slow)

### ISSUE THREAD

**Issue by kerwanp** [kubernetes-sigs/aws-alb-ingress-controller#1123]
Hi,
I have a simple wordpress application running on Kubernetes with a service (NodePort), an Ingress, and the AWS ALB Ingress Controller.

It looks like the AWS ALB Ingress Controller is really slow and take more than 10 seconds for a request to reach the POD.

Is there any way to debug the traffic in the AWS ALB Ingress Controller ? (Like printing the requests)

```yaml
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lexon-b2c-dev
    engine: wordpress
    environment: dev
    tier: frontend
    type: b2c
  name: lexon-b2c-dev
  namespace: websites
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lexon-b2c-dev
    engine: wordpress
    environment: dev
    tier: frontend
    type: b2c
  sessionAffinity: None
  type: NodePort
```

```yaml
# Ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: xxxxxxxxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  generation: 1
  labels:
    app: lexon-b2c-dev
    engine: wordpress
    environment: dev
    tier: frontend
    type: b2c
  name: lexon-b2c-dev
  namespace: websites
spec:
  rules:
  - host: dev.xxxxxxxxxx.com
    http:
      paths:
      - backend:
          serviceName: lexon-b2c-dev
          servicePort: 80
        path: /
status:
  loadBalancer:
    ingress:
    - hostname: xxxxxxxxxx.eu-central-1.elb.amazonaws.com
```

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  generation: 3
  labels:
    app.kubernetes.io/instance: b2c
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: aws-alb-ingress-controller
    helm.sh/chart: aws-alb-ingress-controller-0.1.12
  name: b2c-aws-alb-ingress-controller
  namespace: websites
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: b2c
      app.kubernetes.io/name: aws-alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: b2c
        app.kubernetes.io/name: aws-alb-ingress-controller
    spec:
      containers:
      - args:
        - --cluster-name=xxxxxxxxxx
        - --ingress-class=alb
        - --watch-namespace=websites
        env:
        - name: AWS_ACCESS_KEY_ID
          value: XXXXXXXXXX
        - name: AWS_SECRET_ACCESS_KEY
          value: XXXXXXXXXX
        image: docker.io/amazon/aws-alb-ingress-controller:v1.1.4
        imagePullPolicy: IfNotPresent
        name: aws-alb-ingress-controller
        ports:
        - containerPort: 10254
          name: health
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: b2c-aws-alb-ingress-controller
      serviceAccountName: b2c-aws-alb-ingress-controller
      terminationGracePeriodSeconds: 60
```

> I added some code, I maybe did something wrong in the configuration

Thanks in advance.
