### ISSUE TITLE
Getting 502 when running a deployment rolling update

### ISSUE THREAD

**Issue by idanya** [kubernetes-sigs/aws-alb-ingress-controller#1124]
When running a rolling update of a deployment, the ALB returns a lot of 502's. 
Seems like the ALB is not synced to the actual pod state in k8s.

I can see that when a pod is being replaced, the alb controller registers the new pod in the target group and removes the old one. The problem is that the ALB state is for the new pod is `initial` and for the old one is `draining` - causing the service to be unavailable and return 502.  

Service is completely unavailable when it's a single pod service, with bigger services with multiple pods I can see there is a spike in 502's which resolves itself after a while (all new pods gets to the healthy state in the alb).

Ideally, the old pod should not terminate before the new one gets to a `healthy` state in the ALB. Of course, k8s is not aware of that. 

Is this a known issue? any acceptable workarounds?

**Comment by gaganapplatix** [comment]
You need the readiness gate if you are on flat networking and Pods are direct targets for the ALB. There is a PR sitting around which needs to be merged for this

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/955

Without that the deployment controller will move forward with its rolling updates regardless of whether target groups are up to date with regard to the new pods.

**Comment by wadefelix** [comment]
don't update the service.

**Comment by vedatappsamurai** [comment]
Is there any update on this as #955 is merged now? We've updated ALB Ingress Controller to v1.1.6 and we're still getting 502/504's whenever HPA terminates a pod receiving requests. We kept 30 second sleeps just in case v1.1.6 did not fix it, but we've received 502/504's regardless.

**Comment by M00nF1sh** [comment]
@wadefelix i believe this is fixed with pod readiness probe. 
The caveat is you need to add the pod readiness probe manually for now and do a sleep. 

Sample pod spec:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp
spec:
  replicas: 200
  selector:
    matchLabels:
      app: my-dp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-dp
    spec:
      readinessGates:
      - conditionType: target-health.alb.ingress.k8s.aws/my-ingress_my-dp_80
      containers:
      - name: server
        image: xx
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: The Doctor
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 40"]
      terminationGracePeriodSeconds: 70
```
