### ISSUE TITLE
CertificateNotFound error in logs when changing certificate

### ISSUE THREAD

**Issue by kurtostfeld** [kubernetes-sigs/aws-alb-ingress-controller#1127]
I'm trying to change my https/tls certificate. With the older certificate, everything is working perfectly.

With the newer certificate, I see the following error in the logs:

```text
controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile listener due to CertificateNotFound: Certificate 'arn:aws:acm:us-west-2:114416042199:certificate/c16e5a18-0e07-4d9d-aa93-909458d77e36' not found\n\tstatus code: 400, request id: 09ab79e7-c7e8-4868-ad4d-6dc774f4b4ae
```

The cert is there, I can run the following and see the certificate:

```bash
aws --region us-west-2 acm describe-certificate --certificate-arn 'arn:aws:acm:us-west-2:114416042199:certificate/c16e5a18-0e07-4d9d-aa93-909458d77e36'
```

My suspicion is that the certificate is found but there is some problem or error using the certificate and the error message `CertificateNotFound` is misleading. I could be wrong, but that seems at least possible.

I'm running alb-ingress 1.1.4:

```bash
kubectl -n alb-ingress get pods -o jsonpath="{..image}"
docker.io/amazon/aws-alb-ingress-controller:v1.1.4 amazon/aws-alb-ingress-controller:v1.1.4% 
```

I'm using `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` authentication. Both old/new certificates are in the same AWS region and use the same AWS user account.

A snippet of my ingress yaml:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:114416042199:certificate/c16e5a18-0e07-4d9d-aa93-909458d77e36
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: <redacted>
```

any ideas?
