### ISSUE TITLE
Specify auth config per path

### ISSUE THREAD

**Issue by thrawny** [kubernetes-sigs/aws-alb-ingress-controller#1134]
What I wan't to do is to configure auth for an ingress, in my case using an oidc provider. Then I want to say that for a specific path to not use auth. 

Use case is I have this webapp that I want to have auth for. But it will also receive webhooks on a specific path so this path needs to be kept open.

Can't figure out if this is possible or not using the new advanced routing features.
If I make this ingress with auth for all routes, I can go into the aws gui and just add a rule by hand, and this works. So it is certainly possible to do this with ALBs. But is it possible using only ingress + annotations or what not?

**Comment by pjaol** [comment]
Did you get anywhere with this? 
Have the same question

**Comment by M00nF1sh** [comment]
@thrawny 
The auth annotations can be applied to either ingress or service, the one on service takes priority.
so suppose your Ingress uses different service per path like below, and you only need auth for `/checkout/` but not `/product/`

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ingress
  annotations:  
      alb.ingress.kubernetes.io/auth-idp-oidc: ....
      alb.ingress.kubernetes.io/auth-type: none # can be omitted since it's default
spec: 
  rules:
  - host: dev.example.com
     http:
       paths:
       - path: /product/*
         backend:
           serviceName: product-service
           servicePort: 80
      - path: /checkout/*
        backend:
           serviceName: checkout-service
           servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Service
metadata:
  namespace: default
  name: checkout-service
  annotations:  
     alb.ingress.kubernetes.io/auth-type: cognito # Override auth-type to be cognito here
...
---
apiVersion: extensions/v1beta1
kind: Service
metadata:
  namespace: default
  name: product-service
  annotations:  
     alb.ingress.kubernetes.io/auth-type: none # Can be omitted since it's none on ingress.
...
```
Similarly, you can override other auth annotation on service, and specify common ones on ingress.
