### ISSUE TITLE
Deploying multiple NodePort services results in unwanted R53 records

### ISSUE THREAD

**Issue by paulalex** [kubernetes-sigs/aws-alb-ingress-controller#1142]
I have had the ALB ingress controller running for over a month now and its mostly stable, there does seem to be an intermittent issue whereby I get the IP addresses in the R53 A-record instead of an alias to the ALB's ID.

I am deploying multiple services and this does work but for each additional service I deploy I get another R53 record which I dont need to use, for example I deploy two services `user-service` and `hello-service` both as `NodePort`. 

My ingress looks like:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example
  namespace: NAMESPACE_PLACEHOLDER
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/tags: Service=Demo
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
  labels:
    app: example
spec:
  rules:
    - http:
        paths:
          - path: /user/*
            backend:
              serviceName: user-service
              servicePort: 80
          - path: /*
            backend:
              serviceName: hello-service
              servicePort: 80
```
One of my services, `user-service` is deployed and the ALB and R53 records are created and I can access both services through that URL using either `/user/some_url` or anything else `/*` and this seems to be ok.

However I also get a R53 record created for the `hello-service` because its service type is defined as `NodePort` as well, and in this R53 record its a standard A-record with the IP addresses of my worker nodes listed and I dont want or need this extra DNS record.

All target groups and ALB paths are created as I expect and both services are available through the first URL which is pointing at the ALB.

Is this a bug or is there something I am missing from the documentation to indicate that I do not want extra R53 records created for services? 

I have tried to deploy additional services as `ClusterIP` just to see if this would work but this doesnt seem to make the services routable.

Thanks

**Comment by paulalex** [comment]
I have also noticed that this can cause issues when the route 53 record used for the ALB alias actually doesnt take on the domain name for my app but has `ingress` inserted into it.

I think this happens because one of the R53 records for the services is already created with this as its DNS name and contains the list of ip addresses for the workers in the cluster.

How do I instruct the services not to create R53 records of their own?

I only want the ALB alias record created and not all the others for my services, I didnt spot any annotation that could indicate that I do not want records created for the services themselves which are defined as type NodePort.

**Comment by M00nF1sh** [comment]
@paulalex Hi, are you using external-dns to manage the R53 records?
seems to me the problem is you have configured external-dns to manage R53 for both Ingress & service.
What's your service spec looks like?

**Comment by paulalex** [comment]
@M00nF1sh external DNS is being used to manage the R53 records, service spec below:

```
apiVersion: v1
kind: Service
metadata:
  name: example-rds-python
  labels:
    app: example-rds-python
spec:
  type: NodePort
  ports:
  - name: example-rds-python
    protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    app: example-rds-python
```
