### ISSUE TITLE
How to configure ALB to use LetsEncrypt certificate?

### ISSUE THREAD

**Issue by ipeychev** [kubernetes-sigs/aws-alb-ingress-controller#1143]
Hello,

I'm trying to configure ALB to use an LetsEncrypt certificate, issued by [CertManager](https://cert-manager.io/docs/).

I have an Ingress configuration like:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  namespace: default
spec:
  tls:
  - hosts:
    - myhost.com
    secretName: myhost-com-tls-production
  rules:
  - host: myhost.com
    http:
      paths:
      - path: /
        backend:
          serviceName: ui-service
          servicePort: 80
```

**This works OOTB with Google Cloud Platform** (without even specifying `    kubernetes.io/ingress.class`), **but it doesn't work with ALB** - the request to myhost.com, simply times out. The certificate was successfully issued by Cert Manager.
The logs say:

```
$ kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o "alb-ingress[a-zA-Z0-9-]+")

I0126 09:52:32.800947       1 security_group.go:75] default/ui-ingress: granting inbound permissions to securityGroup sg-024e274984cdd6e29: [{    FromPort: 80,    IpProtocol: "tcp",    IpRanges: [{        CidrIp: "0.0.0.0/0",        Description: "Allow ingress on port 80 from 0.0.0.0/0"      }],    ToPort: 80  }]
```

It seems using ALB with certificates, issued by LetsEncrypt is simply not supported, and we have to use [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/). AWS Certificate Manager is limited - according to the documentation, it supports only DNS and some other monkey-menthod, called "Email Validation". HTTP-01 challenge and [the rest](https://letsencrypt.org/docs/challenge-types/) are not supported.

Is it really impossible to use ALB with certificates, issued by LetsEncrypt?
