### ISSUE TITLE
Http header based route not work

### ISSUE THREAD

**Issue by machao23** [kubernetes-sigs/aws-alb-ingress-controller#1158]
The alb-ingress-controller's version is 1.15. My config like this. 
Alb is created but no listeners.
I don't know the problem's reason. Where is the log location? 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app
  namespace: app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: xxx.com
    alb.ingress.kubernetes.io/certificate-arn: 	xxx
    alb.ingress.kubernetes.io/conditions.adapter-sabre-fort: >
      [{"Field":"http-header","HttpHeaderConfig":{"HttpHeaderName": "fort", "Values":["true"]}}]
spec:
  rules:
    - http:
        paths:
            - backend:
                serviceName: prod
                servicePort: 3000
            - backend:
                serviceName: test
                servicePort: use-annotations
```
