### ISSUE TITLE
How to forward request to specifc k8s service by use-annotation

### ISSUE THREAD

**Issue by machao23** [kubernetes-sigs/aws-alb-ingress-controller#1159]
When using alb.ingress.kubernetes.io/actions, how to set value  to forward request to specifc k8s service?
Like
```
alb.ingress.kubernetes.io/actions.appService: >
        {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"appService","ServicePort":"3001"}]}}
```

**Comment by M00nF1sh** [comment]
Hi, i think you just pasted the correct answer yourself 🤣 .

You can then reference it in ingress like:
```
- path: /xxxxx
            backend:
              serviceName: appService
              servicePort: use-annotation
```
BTW, only use this if you want to use the advanced routing feature(e.g. routing by header/query, etc.), otherwise, stick to the standard ingress like
```
- path: /xxxxx
            backend:
              serviceName: appService
              servicePort: 3001
```
