### ISSUE TITLE
Congito integration - Error with action type 'authenticate-cognito'

### ISSUE THREAD

**Issue by guillemtp** [kubernetes-sigs/aws-alb-ingress-controller#1165]
Enabling the cognito integration in an existing Ingress with ALM produces the following error:

```
E0213 12:55:36.186978       1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile listener due to ValidationError: Action type 'authenticate-cognito' must be one of 'redirect,fixed-response,forward,authenticate-oidc'\n\tstatus code: 400, request id: e3cc4d71-d848-454a-b59e-ab9054497ba5"  "controller"="alb-ingress-controller" "request"={"Namespace":"test","Name":"test"}
```

The part of manifest related to it is the following:

```yaml
metadata:
  annotations:
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:eu-central-1:xxx:userpool/eu-central-xxx","UserPoolClientId":"xxx","UserPoolDomain":"xxxx"}'
    alb.ingress.kubernetes.io/certificate-arn: ' arn:aws:acm:eu-west-3:xxx:certificate/xxxx'
```

I've seen that the message `Action type 'authenticate-cognito' must be one of` could be from AWS. Is there missing any annotation?

**Comment by M00nF1sh** [comment]
@guillemtp 
Hi, which controller version are you using? I cannot reproduce this with v1.1.5:
```
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    a: b
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:us-west-2:283511030707:userpool/us-west-2_OBdkeJ0Za","UserPoolClientId":"xxxx","UserPoolDomain":"m00nf1sh"}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:283511030707:certificate/f58895f2-e71c-4bd1-8f12-cad3efd7b51c
```
I used above setting, and it works fine 🤔

**Comment by guillemtp** [comment]
I confirm that I'm using the version v1.1.5.

I attach the whole ingress file, if some other parameter could have an impact.

```
 iVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:eu-central-1:*****:userpool/****","UserPoolClientId":"****","UserPoolDomain":"******"}'
    alb.ingress.kubernetes.io/certificate-arn: ' arn:aws:acm:eu-west-3:*******:certificate/**********'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'

  name: ingres-monitoring
  namespace: kube-monitoring
spec:
  rules:
  - host: alertmanager.example.com
    http:
      paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - backend:
          serviceName: alertmanager-main
          servicePort: web
  - host: grafana.example.com
    http:
      paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - backend:
          serviceName: grafana
          servicePort: http
  - host: prometheus.example.com
    http:
      paths:
      - backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - backend:
          serviceName: prometheus-k8s
          servicePort: web
```
