### ISSUE TITLE
Backend-protocol annotation applied to a Service does not take a priority 

### ISSUE THREAD

**Issue by bgvladedivac** [kubernetes-sigs/aws-alb-ingress-controller#1174]
Hello,

I am trying to create a single Ingress with a default backend protocol of HTTPS, which works with ArgoCD service, while expose HTTP for Grafana service by providing the "alb.ingress.kubernetes.io/backend-protocol: "HTTP" annotation to the service. The Ingress Controller image is 1.1.5, which schould be latest. 

Based on the notes under https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/ingress/annotation.md

> !!!note - Annotations applied to service have higher priority over annotations applied to ingress. Location column below indicates where that annotation can be applied to. 

Again based on the docs, this annotation could be applied to a Service as well. 

alb.ingress.kubernetes.io/backend-protocol | HTTP \| HTTPS | HTTP | ingress,service
-- | -- | -- | --

Ingress Content:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: "clusteringress"
 namespace: "management"
 annotations:
   kubernetes.io/ingress.class: alb
   alb.ingress.kubernetes.io/scheme: internet-facing
   alb.ingress.kubernetes.io/certificate-arn: xxx
   alb.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: argocd-XXX
    http:
      paths:
      - backend:
          serviceName: "argocd-server"
          servicePort: 443
        path: /*
  - host: grafana-XXX
    http:
      paths:
      - backend:
          serviceName: "prometheus-operator-grafana"
          servicePort: 80
        path: /*

```

The Grafana Service:

```yaml

Name:                     GrafanaXXX
Namespace:                management
Labels:                   app.kubernetes.io/instance=prometheus-operator
                          app.kubernetes.io/managed-by=Tiller
                          app.kubernetes.io/name=grafana
                          app.kubernetes.io/version=6.6.1
                          helm.sh/chart=grafana-5.0.0
Annotations:              alb.ingress.kubernetes.io/backend-protocol: HTTP
                          kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"alb.ingress.kubernetes.io/backend-protocol":"HTTP"},"labels":{"app.kuberne...
Selector:                 app.kubernetes.io/instance=XXX
Type:                     NodePort
IP:                       172.20.216.20
Port:                     service  80/TCP
TargetPort:               3000/TCP
NodePort:                 service  31798/TCP
Endpoints:                10.0.137.211:3000
```

The end result is two target groups created with HTTPS protocol, while my expectation is that I schould have 1 with HTTP and 1 with HTTPS. Grafana has been tested as the only service of the Ingress on HTTP backend-protocol and it works without any issues. 

On the top of the 2 Target Groups sharing the same backend-protocol Grafana ends up with 502 Bad Gateway Status Code, if this could highlight some debugging.
