### ISSUE TITLE
ALB Ingress fails creation. Error: failed to resolve 2 qualified subnets

### ISSUE THREAD

**Issue by nikhils5501** [kubernetes-sigs/aws-alb-ingress-controller#1182]
I am trying to create an Internal ALB that points to a ClusterIP service named `backend-service` on 6000 port. 
These tags were automatically added to my Private subnets when I did kube apply for ingress. 
``` 
kubernetes.io/cluster/EKSCluster     shared
kubernetes.io/role/internal-elb                 true
```
However, I get this error on alb-ingress-controller logs saying:
```"msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to retrieval of subnets failed to resolve 2 qualified subnets. Subnets must contain the kubernetes.io/cluster/\u003ccluster name\u003e tag with a value of shared or owned and the kubernetes.io/role/internal-elb tag signifying it should be used for ALBs Additionally, there must be at least 2 subnets with unique availability zones as required by ALBs. Either tag subnets to meet this requirement or use the subnets annotation on the ingress resource to explicitly call out what subnets to use for ALB creation. The subnets that did resolve were []"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"internal-ingress"}```

My ingress manifest is:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: internal-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":6000}]'
  labels:
    app: test-app
spec:
  rules:
    - host:
      http:
        paths:
          - path: /*
            backend:
              serviceName: backend-service
              servicePort: 6000
```

What am i doing wrong?
