### ISSUE TITLE
Creating duplicated ALBs on AWS

### ISSUE THREAD

**Issue by weslleycamilo** [kubernetes-sigs/aws-alb-ingress-controller#1199]
Hi, 

I've migrated all my pods to a new AWS eks cluster and once I deployed it it started to duplicate the ALB one for the new cluster and other alb for the deleted k8s cluster.

I've created a new ingress as well and saw it create two alb. 

Why is that ? 

Looking into the k8s ingress manifest I see the wrong reference, but it is created automatically :thinking: 

```
status:
  loadBalancer:
    ingress:
    - hostname: internal-ea50810c-cops-copsingress-7a6b-1946681565.us-east-1.elb.amazonaws.com

```

while the new and right ALB is:

`internal-fd66572f-cops-copsingress-7a6b-1966552449.us-east-1.elb.amazonaws.com`

**Comment by M00nF1sh** [comment]
Hi, I think i didn't understand the problem correctly.
Did you create an new Ingress in new cluster? every Ingress will only create a single ALB. (The ALB name is calculated by clusterName+IngressNamespace+IngressName)

**Comment by weslleycamilo** [comment]
hi @M00nF1sh, 

I've 3 ingress which would lead me to 3 ALBs but after my migration to a new cluster it started to happen.

So I am still using the same ingress I used to have before and for purpose of tests I just create this 3° ingress to test if a new ingress would have the same problem.

If I go inside the ALB and look at the rules they are all duplicated as well

**Comment by M00nF1sh** [comment]
Do you have identical Ingress in two clusters(old cluster and new cluster)? If so, it will be two ALB since it's different Ingress(same spec in two different cluster)

**Comment by weslleycamilo** [comment]
@M00nF1sh  I've not. I've deleted the old cluster so now I've one k8s cluster with 3 different ingress, 1 ingress per namespace.

**Comment by weslleycamilo** [comment]
Here are the flags I'm using to run the aws alb ingress controller.

I've upgraded to the last image and got not difference in the problem.
```
      - args:
        - --cluster-name=-k8s-prod
        - --ingress-class=alb
        - --aws-region=us-east-1
        - --aws-vpc-id=vpc-11223a75
        image: docker.io/amazon/aws-alb-ingress-controller:v1.1.5
        imagePullPolicy: IfNotPresent
```
