### ISSUE TITLE
Alb ingress not working - ListenerNotFound

### ISSUE THREAD

**Issue by anothersrewhocancode** [kubernetes-sigs/aws-alb-ingress-controller#1221]
**ingress manifest**
```
1	apiVersion: extensions/v1beta1
2	kind: Ingress
3	metadata:
4	  name: jenkins-alb-ingress
5	  namespace: jenkins
6	  annotations:
7	    kubernetes.io/ingress.class: alb
8	    alb.ingress.kubernetes.io/scheme: internet-facing
9	    alb.ingress.kubernetes.io/success-codes: 302
10	    kubernetes.io/ingress.class: "alb"
11	    alb.ingress.kubernetes.io/subnets: subnet-xxxxxxx, subnet-xxxxxxx
12	    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:xxxxxxxxxxx:certificate/cxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
13	    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
14	    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
15	    iam.amazonaws.com/role: arn:aws:iam::xxxxxxxxxxx:role/alb_user_role
16	  labels:
17	    app: jenkins-ingress
18	spec:
19	  rules:
20	    - http:
21	        paths:
22	          - path: /jenkins
23	            backend:
24	              serviceName: jenkins
25	              servicePort: 80

```

**error**: (logs of alb ingress)
failed to reconcile listeners due to failed to reconcile rules due to ListenerNotFound: One or more listeners not found`

The ALB got created however i am getting the above error
1) Its not pointing to any target groups. do i need to mention target groups anywhere?

**Comment by M00nF1sh** [comment]
Is there more logs after the listenerNotFound error?

BTW, something abnormal in your ingress spec
1. `alb.ingress.kubernetes.io/success-codes: 302`. numbers must be quoted in yaml like `alb.ingress.kubernetes.io/success-codes: "302"`, otherwise, all other annotation will lost. (check it by kubectl get xxx -o yaml)
2. `iam.amazonaws.com/role: arn:aws:iam::xxxxxxxxxxx:role/alb_user_role` i don't know which component uses it.
3. you have two "kubernetes.io/ingress.class"

**Comment by M00nF1sh** [comment]
feel free to reopen if the issue still exists after above correction :D

**Comment by syahdeini** [comment]
Hi I got the same error
```

Warning  FailedDeployModel  10m  ingress  Failed deploy model due to failed to create listener rule: InternalFailure:
           status code: 500, request id: 334139ed-eff5-48c8-90b3-86a5b6e63ee4
  Warning  FailedDeployModel  9m41s  ingress  Failed deploy model due to failed to create listener rule: InternalFailure:
           status code: 500, request id: bff66d8c-9671-4384-b1dd-81c9c05da462
```

This is my ingress
  ```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=test-app,Owner=globalAnalytics
    # For each `listen-ports` object defined an ALB lister is created
    # For each listener created the rules defined in `spec` apply with some basic caveats
    # SSL redirect rule is applied only to the HTTP listener.  Cognito authentication rule
    # is applied to the HTTPS listener
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    # Detailed redirect settings
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # Authentication type must be cognito
    alb.ingress.kubernetes.io/auth-type: cognito
    # Required parameter for ALB/Cognito integration
    alb.ingress.kubernetes.io/auth-scope: openid
    # Session timeout on authentication credentials
    alb.ingress.kubernetes.io/auth-session-timeout: "3600"
    # Session cookie name
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    # Action to take when a request is not authenticated
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    # Cognito parameters required for creation of authentication rules
    # The subdomain name only is sufficient for `UserPoolDomain`
    # e.g. if `FQDN=app.auth.ap-northeast-1.amazoncognito.com` then `UserPoolDomain=app`
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:xxxx:xxxx:userpool/xx-xxx","UserPoolClientId":"xxx","UserPoolDomain":"xxm"}'
    # ACM certificate ARN for your SSL domain
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:xx-xxx:xxxx:certificate/xxxx
  creationTimestamp: null
  generation: 1
  labels:
    app: abc
  name: app-ingress
spec:
  rules:
    - http:
        paths:
          # This first path should perform an ssl-redirect as below
          - backend:
              serviceName: ssl-redirect
              # Configured via the redirect settings in the annotations
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: app-service
              servicePort: 80
```

I seriously have no idea why is this happening, since my other ingress works fine.
