### ISSUE TITLE
Redirect one domain to another using HTTPS 

### ISSUE THREAD

**Issue by tarpanpathak** [kubernetes-sigs/aws-alb-ingress-controller#1224]
Hi, 

This is more of a general guidance question so any help or feedback is much appreciated - we are currently using the Kubernetes ALB Ingress Controller and have a need to redirect one domain to another temporarily using HTTPS. My question is - is this possible or would we have to switch to Nginx? Note: I have glanced through several articles but am unable to find a concrete example so please confirm. If it helps, here's the scenario we need to implement: 

```sh
https://foo.com -> https://bar.com -> service -> pod 
```
Here's the configuration we are currently using: 
```yaml 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: someApp
  # List of annotations: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/tags: app=someApp
    alb.ingress.kubernetes.io/target-type: instance
    kubernetes.io/ingress.class: alb
  labels:
    app: someApp
spec:
  rules:
  - host: foo.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: foo
          servicePort: 80
``` 
The config above works as expected but how can we update it to support the "domain redirect" requirement?
