### ISSUE TITLE
Not able to create create alb in monitoring namespace 

### ISSUE THREAD

**Issue by vrathore18** [kubernetes-sigs/aws-alb-ingress-controller#1247]
I am stuck at an issue, not able to find whats the issue. I have alb-ingress-controller and external-dns as well. And everything is working fine but when I am trying to expose a service in monitoring namespace. I am not able to do so.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /liveness
    alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
spec:
  rules:
    - host: grafana.xxxx.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: prometheus-operator-grafana
              servicePort: 80
```

This would create an ingress in monitoring namespace and the service "prometheus-operator-grafana" is present in same namespace. I can see the alb is getting created but not the dns and even from alb I am not able to access the service.

My question is: As I can see ALB is getting created to problem is with external-dns? I even tried creating the same ingress in default and pointing the service name to prometheus-operator-grafana.monitoring.svc.cluster.local but Its throwing me an error that the service name is not as per the dns.
