### ISSUE TITLE
Using query string rule with service inside cluster

### ISSUE THREAD

**Issue by amitde69** [kubernetes-sigs/aws-alb-ingress-controller#1266]
Hey,
I have a kubernetes cluster running on EKS (version 1.14) and I am using the ALB AWS Ingress Controller and Im trying to create a query string condition pointing to a service inside the cluster.
the Ingress Annotations page in the documentation says "ServiceName/ServicePort can be used in forward action(advanced schema only)." 

I cant seem to find what is the advanced schema. 
does anyone know how to make this kind of thing work or where do I enable advanced schema ?

alb ingress controller version: v1.1.7
EKS version: 1.14
my annotations:
```
alb.ingress.kubernetes.io/actions.kccproxy: '{"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"kccproxy","ServicePort":"80"}]}}'
alb.ingress.kubernetes.io/conditions.kccproxy: '[{"Field":"query-string","QueryStringConfig":{"Values":[{"Key":"test","Value":"test"}]}}]'

    - http:
        paths:
          - backend:
              serviceName: kccproxy
              servicePort: use-annotation  
```
and the error Im getting from the ingress controller:
```
1 controller.go:217] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile l
isteners due to failed to reconcile rules due to failed modifying rule 12 on arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxxx:listener/app/xxxxxxxxxxxx/xxxxxxx due to ValidationError: '' is not a valid target
group ARN\n\tstatus code: 400, request id: xxxxxxxxxxxxxxx"  "controller"="alb-ingress-controller" "reques
t"={"Namespace":"default","Name":"int-alb"}
```

what am I doing wrong or how do I enable advanced schema?

Thanks :)
