### ISSUE TITLE
Rules are deleted by 1.1.6 when using redirect actions

### ISSUE THREAD

**Issue by billputer** [kubernetes-sigs/aws-alb-ingress-controller#1274]
I'm using a host-based redirect action as [documented here](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#actions). Specifically, I'm redirecting from one domain to another based on the host-header.

When I upgraded to 1.1.7, I found that all of the rules *except for the redirect* were deleted from my ALB. After some testing, I found that the rules are created correctly in 1.1.5 and previous versions, but not in 1.1.6+.

Here's the relevant excerpts from my config:
```yaml
alb.ingress.kubernetes.io/actions.domain-redirect: '{"RedirectConfig":{"Host":"target-host.example.com","Port":"443","Protocol":"HTTPS","StatusCode":"HTTP_301"},"Type":"redirect"}'
alb.ingress.kubernetes.io/conditions.domain-redirect: '[{"Field":"host-header","HostHeaderConfig":{"Values":["test-redirect.example.com"]}}]'
```
```yaml
spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: domain-redirect
          servicePort: use-annotation
      - path: /v1/*
        backend:
          serviceName: backend
          servicePort: 8080
      - path: /ws/*
        backend:
          serviceName: websocket
          servicePort: 8000
      - path: /*
        backend:
          serviceName: frontend
          servicePort: 80
```
Here's the resulting rules, before and after upgrading to 1.1.6.
## Rules in 1.1.5:
![rules-v1 1 5](https://user-images.githubusercontent.com/60652/82948941-9771a500-9f57-11ea-88d4-ca6b88dda1fe.png)
## Rules in 1.1.6
![rules-v1 1 6](https://user-images.githubusercontent.com/60652/82948956-9cceef80-9f57-11ea-98c7-b2ae3fc6cce7.png)

It's my belief that this is a bug introduced by #1162, which adds behavior to detect unconditional redirects and delete any rules after them.
