### ISSUE TITLE
unable to use wildcard in host key of ingress yaml

### ISSUE THREAD

**Issue by bhaweshintouch** [kubernetes-sigs/aws-alb-ingress-controller#1278]
how to write this rule in alb:(attached screenshot).
<img width="1202" alt="Screenshot 2020-05-28 at 5 01 52 PM" src="https://user-images.githubusercontent.com/5381105/83136407-10622f80-a105-11ea-82a8-c5567e2677b6.png">

`error msg: The Ingress "pub-ext" is invalid: spec.rules[0].host: Invalid value: "qa.*.mydomain.co": a wildcard DNS-1123 subdomain must start with '*.', followed by a valid DNS subdomain, which must consist of lower case alphanumeric characters, '-' or '.' and end with an alphanumeric character (e.g. '*.example.com', regex used for validation is '\*\.[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

**Comment by M00nF1sh** [comment]
@bhaweshintouch 
Hi, it's a limitation imposed by k8s Ingress api. however, we do have a "tricky" annotation to bypass it.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/conditions.my-svc-name: >
      [{"Field":"host-header","HostHeaderConfig":{"Values":["qa.*.mydomain.co"]}}]
spec:
  rules:
    - http:
        paths:
          - path: /test/*
            backend:
              serviceName: my-svc-name
              servicePort: 80
```
