### ISSUE TITLE
X-Forwarded-* headers are not passed

### ISSUE THREAD

**Issue by jughead** [kubernetes-sigs/aws-alb-ingress-controller#1305]
I've installed a simple httpbin (https://github.com/postmanlabs/httpbin) service to check if X-Forwarded-Proto header is passed from ALB. According to this documentation https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html#request-routing it must be supported.

However it doesn't return them:

```
$ curl -H "Host: test.staging.example.com" https://db863288-default-httpbin-34b6-1237199957.eu-west-1.elb.amazonaws.com/headers
{
  "headers": {
    "Accept": "*/*", 
    "Content-Length": "0", 
    "Host": "test.staging.example.com", 
    "User-Agent": "curl/7.70.0", 
    "X-Amzn-Trace-Id": "Root=1-5ef53771-9cc00b44b9570f4082ba5c39", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "3fad25f5e1ed70e1", 
    "X-B3-Traceid": "d7f279e8734a22133fad25f5e1ed70e1"
  }
}
```

### Service configuration:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        - image: docker.io/kennethreitz/httpbin
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/actions.redirect:
      '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:.....
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/success-codes: "404"
    kubernetes.io/ingress.class: alb
  name: httpbin
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: redirect
              servicePort: use-annotation
            path: /*
    - host: "test.staging.example.com"
      http:
        paths:
          - backend:
              serviceName: httpbin
              servicePort: 80
            path: /*
```

### Kubernetes environment
AWS EKS (Kubernetes 1.16)
aws-alb-ingress-controller 1.1.6
