### ISSUE TITLE
Limit access by IP

### ISSUE THREAD

**Issue by marcoacarvalho** [kubernetes-sigs/aws-alb-ingress-controller#1309]
Sorry if here is not the right place to ask.
In the example bellow the variable {{ .Values.albServiceName }} will be replaced based on the environment as follows:
PROD env -> 'rule-404'
DEV env -> 'ssl-redirect'
QA env -> 'rule-only-allowed-ips'

PROD and DEV are working as expected, but I'm having a hard time with QA (rule-only-allowed-ips)
The idea is to be the same as 'ssl-redirect' but allowing only the IPs on the conditions access */swagger.
I hope this make sense.
Any sugestions?

Thanks in advance.

```yaml
{{- if .Values.albIngress.enabled -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "test-prod-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type":"redirect","RedirectConfig":{"Protocol":"HTTPS","Port":"443","StatusCode":"HTTP_301"}}'
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/actions.rule-404: >
      {"Type":"fixed-response","FixedResponseConfig":{"ContentType":"text/plain","StatusCode":"404","MessageBody":"Not Found"}}
    alb.ingress.kubernetes.io/conditions.rule-only-allowed-ips: >
      [{"Field":"source-ip","SourceIpConfig":{"Values":["89.XXX.XXX.0/21"]}}]
  labels:
    app: test
spec:
  tls:
    - hosts:
        - {{ .Values.fqdn }}
  rules:
    - host: {{ .Values.fqdn }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /testDataService/swagger*
            backend:
              serviceName: {{ .Values.albServiceName }}
              servicePort: use-annotation
          - path: /userService/swagger*
            backend:
              serviceName: {{ .Values.albServiceName }}
              servicePort: use-annotation
          - path: /notificationService/swagger*
            backend:
              serviceName: {{ .Values.albServiceName }}
              servicePort: use-annotation
          - path: /userService*
            backend:
              serviceName: "user-service"
              servicePort: 80
          - path: /testDataService*
            backend:
              serviceName: "test-data-service"
              servicePort: 80
          - path: /notificationService*
            backend:
              serviceName: "notification-service"
              servicePort: 80
          - path: /*
            backend:
              serviceName: "ui-service"
              servicePort: 80
{{- end }}
```
