### ISSUE TITLE
Cannot reach ClusterIP pods with target-type: ip

### ISSUE THREAD

**Issue by agaudreault-jive** [kubernetes-sigs/aws-alb-ingress-controller#1325]
Hi, I am trying to configure the alb-ingress-controller and I was wondering what should be the recommended/production way to use aws-alb-ingress-controller to expose pods via Ingress. Should they be of type `NodePort`, `LoadBalancer` or `ClusterIP` ?

My goal is to have a single ALB with multiple Route53 A records associated to it. Then the ALB listener redirects traffic to the proper Target Group based on the host and path. Finally, the Target Group redirects the request to the cluster and the k8s Ingress redirects it to the pods.

When I specify the `target-type: ip` annotations on my ingress object with a ClusterIP pod, the target group seems to be created properly, but the instance does not seem to be healthy. My guess is that the IP `10.104.24.60` only exist in the cluster. 

![image](https://user-images.githubusercontent.com/47184027/87950400-42dd3880-ca75-11ea-9a8d-1a031f66df7b.png)

```
NAME                                           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
prometheus-operator-grafana                    ClusterIP   172.20.39.134   <none>        80/TCP                       17d
```

```
NAME                                          READY   STATUS    RESTARTS   AGE   IP             NODE                            NOMINATED NODE   READINESS GATES
prometheus-operator-grafana-9658649f8-hdsx8   2/2     Running   0          17d   10.104.24.60   ip-10-104-24-175.ec2.internal   <none>           <none>
```

```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/target-type: ip
      kubernetes.io/ingress.class: alb
    name: prometheus-operator-grafana
    namespace: monitoring
  spec:
    rules:
    - host: grafana.tools.example.com
      http:
        paths:
        - backend:
            serviceName: prometheus-operator-grafana
            servicePort: 80
          path: /
  status:
    loadBalancer:
      ingress:
      - hostname: internal-monitoring-promet-1234567.us-east-1.elb.amazonaws.com
```

The EKS cluster is pretty much vanilla and I have installed aws-alb-ingress-controller and aws-external-dns. I saw some reference to the [ENI](https://github.com/aws/amazon-vpc-cni-k8s) in the doc and I was wondering if it was necessary having it. It seems like the limit of IP that can be exposed is quite low.
