### ISSUE TITLE
Can't use readinessGates 

### ISSUE THREAD

**Issue by UlyssesCB** [kubernetes-sigs/aws-alb-ingress-controller#1348]
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"clean", BuildDate:"2020-05-06T05:09:48Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

**Controller Version:** aws-alb-ingress-controller:v1.1.8 

```
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  labels:
    app: kong-ingress
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - name: https
    port: 443
    targetPort: 8000
    protocol: TCP
  selector:
    app: kong-ingress
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kong-alb-ingressgateway
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: ---
    alb.ingress.kubernetes.io/certificate-arn: ---
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: '200,301,404'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: ---
  labels:
    app: alb-kong-ingressgateway
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
        - path: /*
          backend:
              serviceName: kong-proxy
              servicePort: https
  tls:
      - hosts:
          - "---"
```
**deployment.yaml**
```
   ...
   readinessGates:
      - conditionType: target-health.alb.ingress.k8s.aws/kong-alb-ingressgateway_kong-proxy_https
 ...
```

The controller looks to be working fine, but I still can't make the `readinessGates` work.

``` 
    message: corresponding condition of pod readiness gate "target-health.alb.ingress.k8s.aws/kong-alb-ingressgateway_kong-proxy_https"
      does not exist.
    reason: ReadinessGatesNotReady
    status: "False"
    type: Ready
```
I've already tried with named ports ```target-health.alb.ingress.k8s.aws/load-balancer-tg-ready"```

I'm following [this](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/ingress/pod-conditions.md) example. Is there any reason for the example to be using headless service and `target-type: ip`  ?
