### ISSUE TITLE
Issue with ALB  HTTPS listener and HTTP backend service

### ISSUE THREAD

**Issue by dusansusic** [kubernetes-sigs/aws-alb-ingress-controller#1395]
I have problems setting up ingress controller. I have multiple services and one ALB. The problematic service needs to be available at `https://x.mydomain.com` but backend service is listening on http.

Here is configuration:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:111111111111:certificate/xxxxxx
    alb.ingress.kubernetes.io/inbound-cidrs: "0.0.0.0/0"
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  labels:
    name: dev-ingress
  name: dev-ingress
spec:
  rules:
  - host: x.mydomain.com
    http:
      paths:
      - backend:
          serviceName: x-svc
          servicePort: 80
        path: /*
  - host: y.mydomain.com
    http:
      paths:
      - backend:
          serviceName: y-svc
          servicePort: 443
        path: /*
status:
  loadBalancer:
    ingress:
    - hostname: 1234567899876543.us-east-2.elb.amazonaws.com
```

Here is `x-svc` config:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds = 30
  labels:
    name: x-svc
  name: x-svc
  namespace: default
spec:
  clusterIP: 172.20.245.155
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: x-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Here is `y-svc` config:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "10"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "5"
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds = 15
  labels:
    name: y-svc
  name: y-svc
  namespace: default
spec:
  clusterIP: 172.20.190.55
  ports:
  - port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: y-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Service `y.mydomain.com` works as expected and it is reachable on `https://y.mydomain.com`.

In front of my domain is Cloudflare and it returns `502` when i try to reach `https://x.mydomain.com`. SSL mode is set to `Full`.

What am I missing in this setup? 

```
|CloudFlare|
------------
|     ALB   | <- HTTPS
------------
|     SVC   | <- HTTP
------------
|     POD   | <- HTTP 
------------
````
When I curl for `http://x-svc.default.svc.cluster.local` from any pod, i get good response.
