### ISSUE TITLE
[v2] loadbalancer sg is not added to inbound rule in worker sg

### ISSUE THREAD

**Issue by cw-sakamoto** [kubernetes-sigs/aws-alb-ingress-controller#1487]
I was running a sample of https://github.com/kubernetes-sigs/aws-alb-ingress-controller/tree/master/docs/examples/2048 
 with `2.0.0-rc2` and it wasn't working, so I found that the loadbalancer sg was not being added to the worker's sg and the health check was not passing.

Is this a specification..?

```
apiVersion: v1
kind: Service
metadata:
  name: "service-2048"
  namespace: "test"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: "2048"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress"
  namespace: "test"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: test
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-XXX
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8080}]'
    alb.ingress.kubernetes.io/healthcheck-port: '80'
    alb.ingress.kubernetes.io/healthy-threshold-count: '3'
    alb.ingress.kubernetes.io/subnets: subnet-XXX,subnet-XXX,subnet-XXX
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-2048"
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
  namespace: "test"
spec:
  selector:
    matchLabels:
      app: "2048"
  replicas: 2
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: "2048"
        ports:
        - containerPort: 80
```

I tried with `alb.ingress.kubernetes.io/target-type: instance` and `NodePort` but it didn't work.
