### ISSUE TITLE
Ingress cross-namespaces

### ISSUE THREAD

**Issue by cesartl** [kubernetes-sigs/aws-alb-ingress-controller#329]
After reading this [issue](https://github.com/kubernetes/kubernetes/issues/17088) I thought it would be possible to:

* have one ingress controller for the cluster
* have one ingress resource per namespace
* Have a single AWS ALB that can serve traffic into multiple namespaces

I did something like that:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-api
  namespace: test
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: ***
spec:
  rules:
  - host: test-api.foo.com
    http:
      paths:
      - path: /**
        backend:
          serviceName: backend
          servicePort: 8999
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: staging-api
  namespace: staging
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: ***
spec:
  rules:
  - host: staging-api.foo.com
    http:
      paths:
      - path: /**
        backend:
          serviceName: backend
          servicePort: 8999
```

However when I tried with `alb-ingresss-controller` I get 2 different ALB in AWS.

Would it be possible to have a single ALB that routes traffic into multiple namespaces?

**Comment by Dgadavin** [comment]
I also was very disappointed about that. Because if we create new ALB for every Ingress what the reason to use it, we can use ELB

**Comment by cesartl** [comment]
yes same here. I was looking at ALB ingress precisely to reduce the number of ELB that we run.

Is there any update on this issue?

**Comment by Dgadavin** [comment]
@cesartl  I found that if you need to add more services to the ingress without creating new ALB you need to add more `rules` into ingess.yml file. This will create Traget group and add it into existing ALB.

**Comment by cesartl** [comment]
Hi @Dgadavin, does that work even if they are not in the same namespace? Let's say I have one service in a `test` namespace and one in a `prod` namespace. I'm not sure how to target those services.

**Comment by Dgadavin** [comment]
Don't think so because it will break the kubernetes concepts

**Comment by cesartl** [comment]
I've written what I did on [Medium](https://medium.com/@cesar.tronlozai/save-on-your-aws-bill-with-kubernetes-ingress-148214a79dcb).

**Comment by bigkraig** [comment]
I'm going to close this and tracking the feature request in #298. I'm of the opinion that it conflicts with the concepts but its clearly something people want to have and since ALBs are not free, I understand and think we should support it.

**Comment by marcossv9** [comment]
Is there any plan to support this kind of use case? I'm having the same issue.

I have one ALB for each of the namespaces created on the cluster. It would be very useful if we can use same ingress (ALB) for multiple namespaces.

**Comment by shuttr** [comment]
I tried to use ExternalName stubs  the other day and the controller didn't grok that too well :(

**Comment by g3gurung** [comment]
I only have one ingress which has a nginx backend in the same default namesapce and from the nginx's configuration I route to any namespace services i want. It is working fine in my production cluster.

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  backend:
    serviceName: nginx-svc
    servicePort: 80
```

**Comment by sureshappana** [comment]
@g3gurung can you elaborate what do you mean by nginx backend here?

**Comment by os-virtualretail** [comment]
Any update on this issue?

**Comment by sirlori** [comment]
@os-virtualretail I did not have time to check thoroughly if this solution was already proposed elsewhere but here is how I managed to get around this "limitation" without using any other ingress type, only ALB.

Basically,  it is possible to create a single Ingress resource in any namespace, let's say "default", annotating it like this `"alb.ingress.kubernetes.io/group.name" = "<PUT_HERE_GROUP_NAME>"`. 
After the ingress is created, an ALB will be spawned and it is then possible to add any Ingress resource in any namespace != "default" by also annotating them in the same way. Then, the controller will take care of merging the various different rules of every ingress from the group.

You can tweak the order of how rules will get merged by using the annotation `"alb.ingress.kubernetes.io/group.order"`.

Example: 

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: main-ingress
    alb.ingress.kubernetes.io/group.order: "1"
    alb.ingress.kubernetes.io/ip-address-type: ipv4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/ingress.class: alb
  name: main-ingress
  namespace: default
spec:
  rules:
  ...
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: main-ingress
    alb.ingress.kubernetes.io/group.order: "30"
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
  name: service-ingress
  namespace: test
spec:
  rules:
  - host: test.xxx
    http:
      paths:
      - backend:
          serviceName: service
          servicePort: xxxx
```
I hope this can be helpful for someone 😄
