### ISSUE TITLE
ALB is not created with correct IP address type (dualstack, ipv4)

### ISSUE THREAD

**Issue by bradreardon** [kubernetes-sigs/aws-alb-ingress-controller#395]
Was tinkering around with enabling IPv6 on our ALBs and noticed that setting `alb.ingress.kubernetes.io/ip-address-type: dualstack` in the annotations for my ingress resource did not result in the ALB being created with dualstack networking on AWS, but always ipv4.

Relevant annotations from my ingress resource:
```
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-xxx, subnet-xxx
    alb.ingress.kubernetes.io/security-groups: sg-xxx
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/healthcheck-path: /xxx
    alb.ingress.kubernetes.io/ip-address-type: dualstack
```
