### ISSUE TITLE
Support IngressBackend configuration

### ISSUE THREAD

**Issue by ehbello** [kubernetes-sigs/aws-alb-ingress-controller#405]
Hello. I am not sure if this is a bug or a misconfiguration by my side. However, I can't configure the default rule for a listener.

According to the Kubernetes documentation for [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#types-of-ingress) resources, the right way to configure that is:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: testsvc
    servicePort: 80
```
In my case, I mixed this 'single service' example with another specific rules. My resulting configuration is similar to:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  backend:
    serviceName: testsvc0
    servicePort: 80
  rules:
  - host: svc1.example.com
    http:
       paths:
       - backend:
           serviceName: testsvc1
           servicePort: 81
  - host: svc2.example.com
    http:
       paths:
       - backend:
           serviceName: testsvc2
           servicePort: 82
```
With this configuration, the default action is forwarded to `testsvc1` instead to `testsvc0`. I also tried to add the following rule without hosts and paths like this without success:
```
   - http:
       paths:
       - backend:
           serviceName: testsvc0
           servicePort: 80
```
Any clue about this unwanted behaviour?

I attach a screenshot of a real case.

![screenshot_20180622_101050](https://user-images.githubusercontent.com/172758/41769121-2b6f2ad4-7606-11e8-9af3-1d40ce378961.png)
