### ISSUE TITLE
 Ingress with routes always falls back to default rule.

### ISSUE THREAD

**Issue by ishaannarang** [kubernetes-sigs/aws-alb-ingress-controller#450]
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-1, subnet-2
    alb.ingress.kubernetes.io/security-groups: sg-1
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
  - host: abc.net
      http:
        paths:
      - path: /
        backend:
          serviceName: jena-fu
          servicePort: 3030
      - path: /svc2
        backend:
          serviceName: svc2
          servicePort: 8080

When I hit abc.net, I am able to access jena-fu service, but when I hit abc.net/svc2, I am not able to access svc2. I tried /svc2* as well, same result.

**Comment by chrisckchang** [comment]
i'm also seeing the same behavior - only the service for the default path is working.

**Comment by zijadmop** [comment]
Have the same issue, but with host based routing. As soon as I remove the path part from ALB using AWS console, everything works properly.

**Comment by kevinsookocheff-wf** [comment]
I'm observing the same issue. The second path is never routed to. I tried `/svc2`, `/svc2/`, `/svc2/*` to no effect.

**Comment by kevinsookocheff-wf** [comment]
I'm actually curious if anyone has gotten path-based routing to work at all? With the configuration below for a single backend I can access the service using the provisioned load balancers DNS, but receive a 404 for the load balancer `DNS/echoserver`

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-<redacted>, subnet-<redacted>, subnet-<redacted>
    alb.ingress.kubernetes.io/security-groups: sg-<redacted>
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
  - host: echoserver.example.com
    http:
      paths:
      - path: /echoserver
        backend:
          serviceName: echoserver
          servicePort: 80
```

To reproduce, first deploy the echoserver, then:

```bash
$ kubectl apply -f ingress.yaml  # defined above
```

You can then access the echoserver at the Load Balancers DNS `x`, but `x`/echoserver/` returns a 404.
