### ISSUE TITLE
Support for backends on multiple namespaces

### ISSUE THREAD

**Issue by wspi** [kubernetes-sigs/aws-alb-ingress-controller#456]
Hello,

I have a service running on namespace A and other isolated service running on namespace B, but they share the same domain, so I'd like to set them as backends of the same ALB, something like this

```yaml
spec:
  rules:
  - http:
      paths:
      - path: /a
        backend:
          serviceName: "a/app"
          servicePort: 80
      - path: /b
        backend:
          serviceName: "b/app"
          servicePort: 80
```

Thanks
