### ISSUE TITLE
Rule in ALB for default-backend is not created

### ISSUE THREAD

**Issue by cw-sakamoto** [kubernetes-sigs/aws-alb-ingress-controller#506]
alb ingress version: 1.0-beta.4

I created an ingress resource with alb-ingress-controller, the rule for default-backend is not created and the nodeport set for the first ingress resource is set to last of ALB rule.

ALB rule by created alb-ingress-controller in management console.
The rule for "/echo" and last is set to same target group.
<img width="1304" alt="issue_pic1" src="https://user-images.githubusercontent.com/29860510/43436365-297c2dda-94bf-11e8-98ac-a5eb93aebb57.png">

Is it supposed to be such a rule?(I created this manually)
<img width="1406" alt="issue_pic2" src="https://user-images.githubusercontent.com/29860510/43436383-45bac3f8-94bf-11e8-90a1-0d84da8d4065.png">

ingress resource:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-XXXX,subnet-XXXX
    alb.ingress.kubernetes.io/security-groups: sg-XXXXX
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
  - host: example.test.info
    http:
      paths:
      - path: /echo
        backend:
          serviceName: echoserver
          servicePort: 80
```
