### ISSUE TITLE
Error adding targets to target group,InvalidInstanceID: There are multiple interfaces attached to instance

### ISSUE THREAD

**Issue by sashanka-kandala** [kubernetes-sigs/aws-alb-ingress-controller#559]
Deployed alb controller on AWS EKS.
Attached policy to worker nodes.
Used 2048-game example to test.
Below are the config files:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress"
  namespace: "2048-game"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    #alb.ingress.kubernetes.io/security-groups: sg-0941bddfa4d5a39a5
    alb.ingress.kubernetes.io/subnets: subnet-xxxx, subnet-xxxx
  labels:
    app: 2048-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: "service-2048"
          servicePort: 80

```
```
apiVersion: v1
kind: Service
metadata:
  name: "service-2048"
  namespace: "2048-game"
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: "2048"
```
**Getting below error:**

Event(v1.ObjectReference{Kind:"Ingress", Namespace:"2048-game", Name:"2048-ingress", UID:"7c48f85e-a0ad-11e8-99ae-061cda1a6546", APIVersion:"extensions/v1beta1", ResourceVersion:"133013", FieldPath:""}): type: 'Warning' reason: 'ERROR' Error adding targets to target group xxxxxxxxxx: InvalidInstanceID: There are multiple interfaces attached to instance 'i-xxxxxxx'. Please specify an interface ID for the operation instead.
```

And instance security groups are not attached to nodes.

**Comment by Kefa7y** [comment]
I get the same error in here as well.

**Comment by kalelc** [comment]
I have the same error.

**Comment by sa-mao** [comment]
I have the same error.

**Comment by kalelc** [comment]
I was able to fix this problem by leaving the worker node with one interface. 

I use terraform to create the Cluster; that configuration creates 2 ENI. I suppose that the problem is because Ingress cannot resolve which IP can use if the instance has 2.

Ingress Log:

With two ENI
```
Warning  ERROR   19m                aws-alb-ingress-controller  Error adding targets to target group 1be2e68f-ed00840058b4cd19079: InvalidInstanceID: There are multiple interfaces attached to instance 'i-0c24e1e4feb8a231b'. Please specify an interface ID for the operation instead.
           status code: 400, request id: bffb00b8-0ac5-47ca-984d-73742f0ed833
```

Leaving one ENI

```
Normal   MODIFY  19m  aws-alb-ingress-controller  1be2e68f-default-beetrack-3016 tags modified
```

```
10.3.2.227 | 3000 | us-west-2b | healthy
10.3.2.157 | 3000 | us-west-2b | healthy
10.3.2.49 | 3000 | us-west-2b | healthy
10.3.2.154 | 3000 | us-west-2b | healthy
10.3.2.111 | 3000 | us-west-2b | healthy
10.3.2.189 | 3000 | us-west-2b | healthy
```

**Comment by sa-mao** [comment]
@kalelc But it shouldn't matter since we use `alb.ingress.kubernetes.io/target-type: ip` and this will cause the ingress to use the pod IP which should be only one IP?

**Comment by kalelc** [comment]
Yes, but AWS creates one IP by Pod. Example:

```
backend-76cc5f5966-9pw5g   1/1       Running             0          11m       10.3.2.227   ip-10-3-2-134.us-west-2.compute.internal
backend-76cc5f5966-9twf5   1/1       Running             0          11m       10.3.2.111   ip-10-3-2-134.us-west-2.compute.internal
backend-76cc5f5966-m5kld   1/1       Running             0          17h       10.3.2.49    ip-10-3-2-134.us-west-2.compute.internal
backend-76cc5f5966-m8x95   1/1       Running             0          11m       10.3.2.154   ip-10-3-2-134.us-west-2.compute.internal
backend-76cc5f5966-t9px6   1/1       Running             0          11m       10.3.2.189   ip-10-3-2-134.us-west-2.compute.internal
backend-76cc5f5966-wr9rr   1/1       Running             0          11m       10.3.2.157   ip-10-3-2-134.us-west-2.compute.internal
...
```

<img width="570" alt="screen shot 2018-08-24 at 10 25 27 am" src="https://user-images.githubusercontent.com/2523397/44587047-24d30480-a788-11e8-8d8d-4faac5538bf8.png">

**Comment by sashanka-kandala** [comment]
@kalelc
Can you tell me the steps followed to resolve this. How to leave worker node withe one interface.

**Comment by kalelc** [comment]
@sashanka-kandala Yeah, sure. 

1. EC2
2. Select you instance worker.
3. click on the Network Interfaces.
4. In the network Interfaces Menu, there is the option to detach ENI from the instance.

Obviously, that is not the solution to production. When I have tried to recreate the problem building the cluster, sometimes ingress add other Network Interface and I get the same error.

**Comment by M00nF1sh** [comment]
I'm able to reproduce this issue by creating an alb ingress after there are multiple ENI attached to node(can be achieved by creating multiple pods, since each pod will consume one secondary ip)

Will start to investigate the root cause and solve it

**Comment by M00nF1sh** [comment]
This root cause is [alb-ingress controller calls **ModifyInstanceAttribute**](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/734cbf1574222fced2fb38c486713d2c2dd693c5/internal/aws/albec2/ec2.go#L409) when attaching security groups to nodes(which allows alb route traffic into it).
According to https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyInstanceAttribute.html, it can cause errors when nodes already have multiple ENI attached.
I'll change it to use **ModifyNetworkInterfaceAttribute** instead, and submit an PR for this

**Comment by kalelc** [comment]
Ok, Thanks. I'll hope for the fix.

**Comment by ricktbaker** [comment]
Same issue here

**Comment by Jeeppler** [comment]
I have the same issue. I figured out that I only have one eth0 network interface in the beginning. However, the moment I deploy an ingress resource, the AWS ALB Ingress Controller adds two more network interfaces.

EKS cluster is setup and before deploying an ingress resource:
![screenshot from 2018-09-12 16-29-52](https://user-images.githubusercontent.com/2007739/45454551-f3c06280-b6a9-11e8-9fe3-101e80502c14.png)

After deploying an ingress resource:

![screenshot from 2018-09-12 16-14-03](https://user-images.githubusercontent.com/2007739/45454550-f3c06280-b6a9-11e8-8f88-e7b2093e79b2.png)

My AWS Alb Ingress Controller Policy and installation file in Terraform:
```
resource "aws_iam_role_policy_attachment" "aws_alb_ingress_controller_policy_attachment" {
    role       = "${module.eks.worker_iam_role_name}"
    policy_arn = "${aws_iam_policy.aws_alb_ingress_controller.arn}"
}

resource "aws_iam_policy" "aws_alb_ingress_controller" {
  name = "AWSAlbIngressController"
  path = "/"
  policy = "${data.aws_iam_policy_document.aws_alb_ingress_controller_policy_document.json}"

}

data "aws_iam_policy_document" "aws_alb_ingress_controller_policy_document" {
  statement {
    actions = [
      "acm:DescribeCertificate",
      "acm:ListCertificates",
      "acm:GetCertificate"
    ]

    resources = [
      "*"
    ]
  }

  statement {
    actions = [
      "ec2:AuthorizeSecurityGroupIngress",
      "ec2:CreateSecurityGroup",
      "ec2:CreateTags",
      "ec2:DeleteSecurityGroup",
      "ec2:DescribeInstances",
      "ec2:DescribeInstanceStatus",
      "ec2:DescribeSecurityGroups",
      "ec2:DescribeSubnets",
      "ec2:DescribeTags",
      "ec2:DescribeVpcs",
      "ec2:ModifyInstanceAttribute",
      "ec2:RevokeSecurityGroupIngress"
    ]

    resources = [
      "*"
    ]
  }

  statement {
    actions = [
      "elasticloadbalancing:AddTags",
      "elasticloadbalancing:CreateListener",
      "elasticloadbalancing:CreateLoadBalancer",
      "elasticloadbalancing:CreateRule",
      "elasticloadbalancing:CreateTargetGroup",
      "elasticloadbalancing:DeleteListener",
      "elasticloadbalancing:DeleteLoadBalancer",
      "elasticloadbalancing:DeleteRule",
      "elasticloadbalancing:DeleteTargetGroup",
      "elasticloadbalancing:DeregisterTargets",
      "elasticloadbalancing:DescribeListeners",
      "elasticloadbalancing:DescribeLoadBalancers",
      "elasticloadbalancing:DescribeLoadBalancerAttributes",
      "elasticloadbalancing:DescribeRules",
      "elasticloadbalancing:DescribeSSLPolicies",
      "elasticloadbalancing:DescribeTags",
      "elasticloadbalancing:DescribeTargetGroups",
      "elasticloadbalancing:DescribeTargetGroupAttributes",
      "elasticloadbalancing:DescribeTargetHealth",
      "elasticloadbalancing:ModifyListener",
      "elasticloadbalancing:ModifyLoadBalancerAttributes",
      "elasticloadbalancing:ModifyRule",
      "elasticloadbalancing:ModifyTargetGroup",
      "elasticloadbalancing:ModifyTargetGroupAttributes",
      "elasticloadbalancing:RegisterTargets",
      "elasticloadbalancing:RemoveTags",
      "elasticloadbalancing:SetIpAddressType",
      "elasticloadbalancing:SetSecurityGroups",
      "elasticloadbalancing:SetSubnets",
      "elasticloadbalancing:SetWebACL"
    ]

    resources = [
      "*"
    ]
  }

  statement {
    actions = [
      "iam:GetServerCertificate",
      "iam:ListServerCertificates"
    ]

    resources = [
      "*"
    ]
  }

  statement {
    actions = [
      "waf-regional:GetWebACLForResource",
      "waf-regional:GetWebACL",
      "waf-regional:AssociateWebACL",
      "waf-regional:DisassociateWebACL"
    ]

    resources = [
      "*"
    ]
  }

  statement {
    actions = [
      "tag:GetResources"
    ]

    resources = [
      "*"
    ]
  }

  statement {
    actions = [
      "waf:GetWebACL"
    ]

    resources = [
      "*"
    ]
  }
}

resource "null_resource" "install_aws_alb_ingress_controller" {
  provisioner "local-exec" {
    command = "scripts/install-aws-alb-ingress-controller.sh"
  }

  depends_on = ["aws_iam_role_policy_attachment.aws_alb_ingress_controller_policy_attachment", "null_resource.install-helm-tiller"]
}
```
scripts/install-aws-alb-ingress-controller.sh:
```
#!/usr/bin/env bash

# Install the ALB ingress controller using Helm
helm registry install quay.io/coreos/alb-ingress-controller-helm -f configs/aws-alb-ingress-controller-values.yaml
```
configs/aws-alb-ingress-controller-values.yaml:
```
awsRegion: us-east-1

clusterName: cluster

rbac:
  create: true
```
the ingress resource `echoserver-ingress.yaml`. A modified version of the echoserver example from the [walkthrough tutorial](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/walkthrough.md)
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=testing,AWSAlbIngressController=true
spec:
  rules:
    - host: echoserver.ecg-test.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```

the relevant parts of the VPC configuration to autodetect the ALB placement:

```
module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  version = "1.41.0"

  ...

  public_subnet_tags = {
    Subnet = "public"

    # this is a workaround for the case in which terraform is run twice.
    # Otherwise Terraform will remove those tags.
    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "kubernetes.io/role/elb" = ""
  }

  private_subnet_tags = {
    Subnet = "private"

    "kubernetes.io/cluster/${var.cluster_name}" = "shared"
    "kubernetes.io/role/internal-elb" = ""
  }
}
