### ISSUE TITLE
How do I create rule without `path-pattern` ?

### ISSUE THREAD

**Issue by sawanoboly** [kubernetes-sigs/aws-alb-ingress-controller#573]
I thought that using this plugin, I would like to create a rule with only the host header. The definition is as follows.

```
spec:
  backend:
    serviceName: fallback-nginx
    servicePort: 80
  rules:
    - host: myapp1.example.com
      http:
        paths:
          - backend:
              serviceName: myapp1
              servicePort: 80
```

However, path-pattern '/' is automatically added. I want to exclude the path-pattern from the rule, is it possible?

```
$ aws elbv2 describe-rules  --rule-arns arn:aws:elasticloadbalancing:us-west-2:xxxxxx:listener-rule/app/xxxxxx
{
    "Rules": [
        {
            "RuleArn": "arn:aws:elasticloadbalancing:us-west-2:xxxxxx:listener-rule/app/xxxxxx",
            "Priority": "1",
            "Conditions": [
                {
                    "Field": "path-pattern",
                    "Values": [
                        "/"
                    ]
                },
                {
                    "Field": "host-header",
                    "Values": [
                        "myapp1.example.com"
                    ]
                }
            ],
            "Actions": [
                {
                    "Type": "forward",
                    "TargetGroupArn": "arn:aws:elasticloadbalancing:us-west-2:xxxxxx:listener-rule/app/xxxxxx"
                }
            ],
            "IsDefault": false
        }
    ]
}
```
