### ISSUE TITLE
Default backend behavior is different from other ingresses

### ISSUE THREAD

**Issue by lbernail** [kubernetes-sigs/aws-alb-ingress-controller#597]
We are currently using the `ip` target-type and this feature is great

During some testing, I noticed that when I try to access a route with no definition, I end up on one of the backend service and I do not get a 404.

Example:
```yaml
rules:
  - host: echov1.lbernail.us1.staging.dog
    http:
      paths:
      - path: /
        backend:
          serviceName: echov1
          servicePort: 80
  - host: echov2.lbernail.us1.staging.dog
    http:
      paths:
      - path: /
        backend:
          serviceName: echov2
          servicePort: 80
```

When I try to access a host without any rule, I would expect a 404, but I get to the first service (after checking, the default action for the listener is set to the first targetgroup).

After looking at the code it seems that the controller looks for a default backend configured 
with `ingress.spec.backend` and if there is none it uses the first valid backend: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/27f2048c1af4fd5e6a7e31402701e2bddff66862/internal/albingress/albingresses.go#L231

Adding this to the ingress:
```yaml
  backend:
    serviceName: fixed-response-error
    servicePort: use-annotation
```

works great but I wonder if we shouldn't use this as a default if there is no default backend key in the spec
