### ISSUE TITLE
1.0-beta.7 Changes Listener Rules to Fixed 404 Response

### ISSUE THREAD

**Issue by stevenpall** [kubernetes-sigs/aws-alb-ingress-controller#646]
Hi there,

I just tested the new beta tag and unfortunately noticed that all of my ingress load balancers' listener rules were altered to a single fixed response (404) rule instead of pointing at their corresponding target groups. Reverting to `1.0-beta.6` fixed the issue. This seems like a fairly major bug.

I'm wondering if this could be related to [this](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/615) change?

Thanks!

**Comment by bigkraig** [comment]
Yeah that is related to that PR. Can you describe how your ingresses are configured so I can check that there isn't something misconfigured or unexpected?

**Comment by stevenpall** [comment]
Here's a sample ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:some-cert
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-12345678
spec:
  rules:
  - host: test.website.com
    http:
      paths:
      - backend:
          serviceName: test
          servicePort: 80
        path: /
```
