### ISSUE TITLE
Services annotation not honored

### ISSUE THREAD

**Issue by vincentjorgensen** [kubernetes-sigs/aws-alb-ingress-controller#665]
(version is 1.0-beta.7)
When I create a service, it's healthcheck port isn't picked up or honored by the Ingress. Example:
```
---
apiVersion: v1
kind: Service
metadata:
  name: altitude
  namespace: atmosphere
  annotations:
    alb.ingress.kubernetes.io/healthcheck-port: 3979
spec:
  selector:
    service: altitude
  ports:
  - name: altitude
    port: 3978
    targetPort: 3978
    protocol: TCP
  - name: altitude-hc
    port: 3979
    targetPort: 3979
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: depth
  namespace: atmosphere
spec:
  selector:
    service: depth
  ports:
  - name: depth
    port: 3030
    targetPort: 3030
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: altitude-ingress
  namespace: atmosphere
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: atmosphere.example.com
    http:
      paths:
      - path: /altitude/*
        backend:
          serviceName: altitude
          servicePort: 3978
      - path: /
        backend:
          serviceName: depth
          servicePort: 3030
...
```

I expect `altitude`'s TargetGroup to perform healthchecks on port `3979` and for `depth`'s TG to use port `3030`, however, the Service annotation is ignored and both TGs use the traffic port.

Unrelated, but out a curiosity, how do I specify the default rule in the ingress spec?
(edited to add version no)

**Comment by bigkraig** [comment]
That looks like a bug, with regards to the default rule, you would set a `backend` in the `spec`: https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_ingressspec

**Comment by vincentjorgensen** [comment]
@bigkraig Cool Thanks. I got the backend working. Any thoughts on honoring the annotations?

**Comment by chrisvdb** [comment]
I'm trying to deploy a k8s cluster on EKS using aws-alb-ingress and seem to be running into the same issue as described here. What is the current status?

My alb-ingress-controller:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alb-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alb-ingress-controller
    spec:
      containers:
        - args:
            - --ingress-class=alb
            - --cluster-name=eks
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.2
          imagePullPolicy: Always
          name: server
          resources: {}
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: alb-ingress
      serviceAccount: alb-ingress
```

My ingress definition:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "myapp"
  labels:
    app: myapp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: "access_logs.s3.enabled=true,access_logs.s3.bucket=my-bucket,access_logs.s3.prefix=some-path"
    alb.ingress.kubernetes.io/load-balancer-attributes: "routing.http2.enabled=true"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "my-app"
              servicePort: 5001
```

The service works, but:

- no HTTP2 support (AWS console does indicate that the load balancer has HTTP2 support, but does not work on website)
- no access log generated on S3 (correct permissions granted AFAIK)

No errors found in alb-ingress logs: kubectl logs -n kube-system $(kubectl get po -n kube-system | egrep -o alb-ingress[a-zA-Z0-9-]+).

I have deleted all the pods, deleted the ALB and recreated everything, but result is the same.

I use the latest image: aws-alb-ingress-controller:v1.1.2

Thoughts?
