### ISSUE TITLE
Map `/` to `/*`

### ISSUE THREAD

**Issue by rahulwa** [kubernetes-sigs/aws-alb-ingress-controller#667]
I believe `path: /` in ingress object should be treated as `/*` in alb ingress controller implementation.

Most of the upstream projects ([Charts examples](https://github.com/helm/charts/search?q=%22paths%3A+-+path%3A+%2F%22&unscoped_q=%22paths%3A+-+path%3A+%2F%22)) considers ingress path `/` as `/*` and it is so wild assumption that many charts doesn't even provides a way to override it while installing them.

---
alb-ingress-controller version: 1.0-beta.7

**Comment by marcusianlevine** [comment]
Upgrading to `1.0-beta.7` broke our existing deployment of this controller due to this issue: root path rules created on ALBs do not allow any path other than `/`

**Comment by marcusianlevine** [comment]
Found a work-around: if you explicitly set the `path` for your backends to `/*` then the ALB rule will be created as a wildcard

Only downside is the endpoint URLs provided for the ingress by k8s won't work since they will be `.../*`

**Comment by bigkraig** [comment]
You can change the default backend by setting a default backend in the ingress. It’s set outside of the paths. I’m on my phone or I’d dig up an example or the ingress docs, but if you search around you should be able to find it

**Comment by marcusianlevine** [comment]
Originally we had ingress rules of the form:
```
  - host: my-service.example.com
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
```

Which would lead to host-based rules on the ALB which route all paths with `my-service.example.com` in the host header

However after upgrading to `1.0-beta.7` the rules on the ALB were created with "Host is my-service.example.com" AND "Path is `/`"

So now any path other than `my-service.example.com/` gets 404'd by the ALB

By explicitly specifying the `path` key of the ingress rule to `/*` the ALB rule routes any path under the specified host, such as `my-service.example.com/login`:

```
  - host: my-service.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: my-service
          servicePort: 80
```
