### ISSUE TITLE
Feature: Allow setting of priority on actions

### ISSUE THREAD

**Issue by rmn36** [kubernetes-sigs/aws-alb-ingress-controller#695]
Currently when creating a redirect action like shown below there is no way to set the priority of the action i.e. the ordering of how the rules will be evaluated. 
`alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_302"}}'`

AWS supports explicity setting the priority of a rule (https://docs.aws.amazon.com/cli/latest/reference/elbv2/set-rule-priorities.html). It would be helpful to be able to set this priority in the annotation.

`alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_302", "Priority": "1" }}'`

**Comment by M00nF1sh** [comment]
Hi, the priority is based on the order you specified in ingresses. (The priority increases from 1).
So you can make your rule happen appears first in ingress to get priority of 1(which is evaluated first)

The default backend in ingress always get evaluated last.

**Comment by rmn36** [comment]
This is my current ingress.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: airflow-web
  labels:
    app: airflow-web
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: xyz
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443, "HTTP": 80}]'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-2016-08
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '300'
    alb.ingress.kubernetes.io/success-codes: '200,302'
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_302"}}'
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: airflow-web
              servicePort: web
      host: {{ .Values.clusterName }}-{{ .Values.ingress.web.host }}
    - http:
        paths:
          - path: /*
            backend:
                serviceName: redirect
                servicePort: use-annotation
```

Are you suggesting reordering the rules as such:
```
  rules:
    - http:
        paths:
          - path: /*
            backend:
                serviceName: redirect
                servicePort: use-annotation
     - http:
        paths:
          - path: /*
            backend:
              serviceName: airflow-web
              servicePort: web
      host: {{ .Values.clusterName }}-{{ .Values.ingress.web.host }}
```

**Comment by M00nF1sh** [comment]
Yes. This(after your reorder) is the correct way to make http->https redirection work. 
(An implicit fact is that we detected it's an redirect rule and won't apply it to https listener).

@bigkraig Should we offering a simple annotation like alb.ingress.kubernetes.io/force-ssl-redirect? But I don't know how to handle cases like people specified multiple http/http ports.

**Comment by bigkraig** [comment]
I like the idea of a simple annotation but in implementation reality it will become a problem when people have multiple ports or rules. There is already a bit of magic in the redirect rule to prevent loops, and any more is going to mean more confusion down the road.

**Comment by rmn36** [comment]
I like the idea of a simple annotation but I understand the potential for more confusion later. If this can be accomplished currently with proper ordering of rules then I'm fine with no annotation, though I do think more explicit documentation on the use of ordering and how it affects the rules in AWS would be helpful.

**Comment by chary1112004** [comment]
> Hi, the priority is based on the order you specified in ingresses. (The priority increases from 1). So you can make your rule happen appears first in ingress to get priority of 1(which is evaluated first)
> 
> The default backend in ingress always get evaluated last.

Hi, this one is no further work for aws-load-balancer-controller 2.5.2. Do you have any idea to make this work?

Thanks!

**Comment by long-bow** [comment]
> > Hi, the priority is based on the order you specified in ingresses. (The priority increases from 1). So you can make your rule happen appears first in ingress to get priority of 1(which is evaluated first)
> > The default backend in ingress always get evaluated last.
> 
> Hi, this one is no further work for aws-load-balancer-controller 2.5.2. Do you have any idea to make this work?
> 
> Thanks!

It actually works in my case, I'm using aws-load-balancer-controller v2.5.1.
Pay close attention to your config, 
My config looked like this, rules in alb have been created but aws priority rules was different then in ingress config 
`rules:
  - host: host.example.com
    http:
      paths:
        - path: "/foo*/bar"
          pathType: ImplementationSpecific
          backend:
            service:
              name: forward-to-external-dns
              port:
                name: use-annotation
        - path: /
          pathType: Prefix 
          backend:
            service:
              name: app-service
              port:
                number: 9999`
I loked closely at this [comment](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/695#issuecomment-433561663) and added few lines and now priority in aws rules same as in ingress config:
`  rules:
    - host: host.example.com
      http:
        paths:
          - path: "/foo*/bar"
            pathType: ImplementationSpecific
            backend:
              service:
                name: forward-to-external-dns
                port:
                  name: use-annotation
+   - host: host.example.com
+     http:
+       paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: app-service
                port:
                  number: 9999`

**Comment by long-bow** [comment]
> > Hi, the priority is based on the order you specified in ingresses. (The priority increases from 1). So you can make your rule happen appears first in ingress to get priority of 1(which is evaluated first)
> > The default backend in ingress always get evaluated last.
> 
> Hi, this one is no further work for aws-load-balancer-controller 2.5.2. Do you have any idea to make this work?
> 
> Thanks!

It actually works in my case, I'm using aws-load-balancer-controller v2.5.1.
Pay close attention to your config, 
My config looked like this, rules in alb have been created but aws priority rules was different then in ingress config 
```rules:
  - host: host.example.com
    http:
      paths:
        - path: "/foo*/bar"
          pathType: ImplementationSpecific
          backend:
            service:
              name: forward-to-external-dns
              port:
                name: use-annotation
        - path: /
          pathType: Prefix 
          backend:
            service:
              name: app-service
              port:
                number: 9999
```
I loked closely at this [comment](https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/695#issuecomment-433561663) and added few lines :
```
  rules:
    - host: host.example.com
      http:
        paths:
          - path: "/foo*/bar"
            pathType: ImplementationSpecific
            backend:
              service:
                name: forward-to-external-dns
                port:
                  name: use-annotation
+   - host: host.example.com
+     http:
+       paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: app-service
                port:
                  number: 9999
```
and now priority in aws rules same as in ingress config
