### ISSUE TITLE
paths not working

### ISSUE THREAD

**Issue by Toolenaar** [kubernetes-sigs/aws-alb-ingress-controller#699]
Hi I have setup ingress-controller on AWS EKS, but I am having problems resolving paths other then the base /

In the example below / does work correctly however /api does not work.

I am using the same app in this example but I have tested it with other apps running in my cluster aswell, all which dont work on /somethinghere.

Any idea what might be going wrong ?

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "webapp-alb-ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-01e193631sfedsf0a3,subnet-0b0064f88sdffd075,subnet-0252d90sdffdfb77e
    alb.ingress.kubernetes.io/tags: Environment=prod,Team=locali
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: webapp-service
spec:
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
  - http:
      paths: 
        - backend:
            serviceName: localiapi
            servicePort: 4040
          path: /api
        - backend:
            serviceName: localiapi
            servicePort: 4040
          path: /
```
