### ISSUE TITLE
404 default-backend.yaml

### ISSUE THREAD

**Issue by KazuyoshiUeno** [kubernetes-sigs/aws-alb-ingress-controller#702]
We can see the follow command at kubectl Deployments in the [link](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/aade316c0e7e67571012cef1db5281ebf337aed2/docs/setup.md
)

`kubectl create -f https://raw.githubusercontent.com/coreos/alb-ingress-controller/master/examples/default-backend.yaml`

However, default-backend.yaml is currently 404 not found.

Please fix this!

**Comment by M00nF1sh** [comment]
Hi, the document is outdated. Our ingress controller don't need the default backend anymore(it's 404).

You can specify the default backend directly in your ingress resource.
e.g.
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: alb
spec:
  backend:
     serviceName: your-default-backend
     serivcePort: your-default-backend-port
  rules:
  - http:
      paths:
      - path: /testpath
        backend:
          serviceName: test
          servicePort: 80
```
