### ISSUE TITLE
alb.ingress.kubernetes.io/connection-idle-timeout has no effect

### ISSUE THREAD

**Issue by rootd00d** [kubernetes-sigs/aws-alb-ingress-controller#727]
I've been using this controller (1.0-beta.7) for a few weeks now, but recently ran into an issue where I needed the idle timeout to be much greater than the default 60s.

No matter what I do, setting alb.ingress.kubernetes.io/connection-idle-timeout seems to have no effect; either when provisioning new ALBs or updating existing ALBs.

Is there something I'm missing here?

```
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/connection-idle-timeout: "1800"
...
```
