### ISSUE TITLE
create new alb only if there isn't one already associated with the ingress host

### ISSUE THREAD

**Issue by yawboateng** [kubernetes-sigs/aws-alb-ingress-controller#73]
Is it possible to have the controller to only create a new alb if there isn't one already associated with the ingress host?

 reason:
I have one hostname, but the services I want to create rules for are in different namespaces, so I'm using multiple ingress objects, but each ingress object creates a new alb and updates the route53 DNS record to the point the most recent one

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-namespaceAuth
  namespace: auth
spec:
  rules:
  - host: apps.example.com
    http:
      paths:
      - path: /service1InAuthNS/*
        backend:
          serviceName: service1
          servicePort: 443
      - path: /service2InAuthNS/*
        backend:
          serviceName: service2
          servicePort: 443
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-namespaceMonitoring
  namespace: monitoring
spec:
  rules:
  - host: apps.example.com
    http:
      paths:
      - path: /service3InMonitoringNS/*
        backend:
          serviceName: service3
          servicePort: 443
     - path: /
        backend:
          serviceName: service4
          servicePort: 443
```
