### ISSUE TITLE
Port 1

### ISSUE THREAD

**Issue by lee5i3** [kubernetes-sigs/aws-alb-ingress-controller#759]
When creating the ALB in AWS its creating the Target Group with a port 1.. however it works fine like this for some reason

![capture1](https://user-images.githubusercontent.com/176932/49310416-38d78200-f4ac-11e8-9de5-bfbf45be3f25.png)

**Comment by M00nF1sh** [comment]
@lee5i3 this can be changed, but do you have a use case for this 😄

**Comment by sg21210** [comment]
I'm getting a bit confused. I'm also experiencing this and isn't it wrong? Is that setting able to send traffic to the specified NodePort, instead of port 1? I'm also having similar issue. Rule is sending 404 by default, Port is 1, and the I must have missed some important annotation/spec since its update to v1.0.1 (previously 1.0-beta.2) but I couldn't find which makes trouble.

![image](https://user-images.githubusercontent.com/3349143/49713761-806cc380-fc8d-11e8-8073-deb8029b8cf1.png)

Here is the Ingress config I made.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: kong-admin
  labels:
    name: kong-admin
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-e2b3c2a8,subnet-e56bc9b9,subnet-5d05a63a,subnet-7056fa5e,subnet-7814e546,subnet-abc9aba4
    alb.ingress.kubernetes.io/security-groups: sg-0b1c6a7822d89c37b
    alb.ingress.kubernetes.io/tags: Name=kong-admin, app=kong
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:792630841427:certificate/1c7b1362-224d-453c-a9bc-87058a5ce148
    alb.ingress.kubernetes.io/healthcheck-path: /status
spec:
  rules:
  - host: test-kong-admin.pubg.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: open-mongoose-kong-admin
          servicePort: 8001
```
