### ISSUE TITLE
Annotation for basic auth

### ISSUE THREAD

**Issue by ishaannarang** [kubernetes-sigs/aws-alb-ingress-controller#770]
Does aws-alb-ingress-controller has an annotation for basic auth.
For Example: nginx.ingress.kubernetes.io/auth-type: basic

**Comment by M00nF1sh** [comment]
Hi, we don't support basic auth(since alb itself doesn't support it).
However, we'll support OIDP and cognito soon. https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/754

**Comment by M00nF1sh** [comment]
closing, since OIDC and cognito are already supported.
and basic auth is not possible since ALB itself don't support it.

**Comment by heidemn-faro** [comment]
> basic auth is not possible since ALB itself don't support it.

@M00nF1sh Is this still true? It seems supported now: https://stackoverflow.com/a/72039326

**Comment by mbocek** [comment]
Is there any plan for the implementation of basic auth by the controller?

**Comment by ajaydevtron** [comment]
Hello @M00nF1sh ,

Could you please add support of this ?

**Comment by Hadlock** [comment]
It is _sort of_ supported for API calls, but won't trigger a basic auth challenge modal for browsers (human users). You need to configure basic auth manually:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/conditions.b-auth: |
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName":"Authorization","values":["Basic aBcDeFgeTc123456=="]}}]
```

Where aBcDeFgeTc is the output of

```
echo -n 'user:password' | base64
```

Note, the example intentionally has invalid b64, you'll need to generate your own
