### ISSUE TITLE
Multiple ALB's created for the same ingress

### ISSUE THREAD

**Issue by wfaler** [kubernetes-sigs/aws-alb-ingress-controller#773]
Firstly, I'm really happy this project exists, it solves a problem we've had for a good while!

However, I've noticed a few oddities when creating and destroying ingresses using SSL and redirect-to-ssl:
* Primarily, I get two, not one ALB created for a single ingress. Is this intentional?

Other, secondary issues (I'm happy to break these out into separate issues, but will put them here as they are related to the same ingress definition):
* Deletion of an ingress doesn't clean out the Route 53 records created.
* Redirect to SSL doesn't seem to work (something wrong in my definition?)
* Recreating the same ingress again after destruction seems to have issues binding to the desired domain. This is both when not touching Route 53, or when cleaning up Route 53 by hand.

Here is the ingress definition used (redacted):

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:...
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
#    alb.ingress.kubernetes.io/actions.redirect: {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/subnets: subnet-XXXX,subnet-XXX,subnet-XXX
spec:
  rules:
    - host: echo.foodomain.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: use-annotation
```

**Comment by M00nF1sh** [comment]
Hi, so for list of issues:
> 1. Primarily, I get two, not one ALB created for a single ingress. Is this intentional?

No you shouldn't get such behavior. The ALB name is generated by combining clusterName and ingressNamespace and ingressName. And ALB names are always unique.  So you shouldn't get two ALB. Do you mean two ALB instance in AWS or DNS entries for your domain?

> 2. Redirect to SSL doesn't seem to work (something wrong in my definition?)

Yes, you should specify your ingress rule as below:
```yaml
spec:
  rules:
    - host: echo.foodomain.com
      http:
        paths:
          - path: /*      #(use /* instead of / to do wildcard match.)
            backend:
              serviceName: ssl-redirect     #(which matches the actions.ssl-redirect annotation)
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: echoserver
              servicePort: xxxx     # use the real port of your echo server here
```
More details can be found in this guide: https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/

> 3. Deletion of an ingress doesn't clean out the Route 53 records created.

Are you using external-DNS to manage the records? It's an separate project and don't have direct relationship to ingress controller. I'm will to help debug & fix it if the error condition is reproducible.

> 4. Recreating the same ingress again after destruction seems to have issues binding to the desired domain. This is both when not touching Route 53, or when cleaning up Route 53 by hand.

Same as above 😄
