### ISSUE TITLE
Action rules not applied to all listeners.

### ISSUE THREAD

**Issue by stafot** [kubernetes-sigs/aws-alb-ingress-controller#782]
My ALB has 2 listeners (80, 443). Added some action redirect rules but they applied only to first listener. Am I missing something? Is there a way to apply to all listeners, or be able to choose?

**Comment by M00nF1sh** [comment]
Hi, 
What's your action configuration? 
There are [some hacks](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/internal/alb/rs/rules.go#L243
) to make https redirection work, which basically ignore rules that cause infinite redirection

**Comment by stafot** [comment]
``` alb.ingress.kubernetes.io/actions.exampleme-redirect-all-ssl: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "example.com", "Path":"/person/#{path}", "StatusCode": "HTTP_301"}}'
``` 
```
  - host: example.me
    http:
      paths:
      - path: /*
        backend:
          serviceName: exampleme-redirect-all-ssl
          servicePort: use-annotation
```

As I said I have 2 listeners on my alb one on 80 and one on 443. I expected when I add a rule for port for 443 port to be applied on the 443 listener, but unfortunately is applied on 80 Listener and for this reason I experience the following behavior.
`https://example.me` -> `KO` gives 404
`http://example.me` -> `OK` redirects me to the place I instructed

@M00nF1sh Appreciate any feedback.

**Comment by M00nF1sh** [comment]
Hi, so you want to both 80 & 443 to be redirected to somewhere(suppose it's not example.me?)
What's your exampleme-redirect-all-ssl looks like? can you paste it here(replace sensitive domain name with fake one like xxx.example.com)

**Comment by stafot** [comment]
@M00nF1sh I was put it there initially, but lost on some wrong editing of mine :) Sorry, fixing.

**Comment by stafot** [comment]
@M00nF1sh Want me to share the 80 port rule too? Is very similar with the one I shared above.

**Comment by M00nF1sh** [comment]
> @M00nF1sh Want me to share the 80 port rule too? Is very similar with the one I shared above.

sure, the full ingress spec with sensitive information replaced will be best(so i can reproduce and fix it)

**Comment by M00nF1sh** [comment]
Currently i cannot reproduce the error. e.g. both 
http://d560e4e0-testcase-echoserv-456e-466865106.us-west-2.elb.amazonaws.com
and https://d560e4e0-testcase-echoserv-456e-466865106.us-west-2.elb.amazonaws.com
will be redirect to https://example.com

**Comment by stafot** [comment]
@M00nF1sh 
My full spec 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "example-alb-ing"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80, "HTTPS": 443}]'
    alb.ingress.kubernetes.io/subnets: 'subnet-xxx1, subnet-xxx2'
    alb.ingress.kubernetes.io/security-groups: "sg-xx1, sg-xx2"
    alb.ingress.kubernetes.io/certificate-arn: xxx
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/actions.exampleme-redirect-slash: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTP", "Port": "80", "Host": "example.com", "Path":"/", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.exampleme-redirect-all: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTP", "Port": "80", "Host": "example.com", "Path":"/person/#{path}", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.exampleme-redirect-slash-ssl: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "example.com", "Path":"/", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.exampleme-redirect-all-ssl: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "example.com", "Path":"/person/#{path}", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.yelp-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTP", "Port": "80", "Host": "port.example.com", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.yelp-redirect-ssl: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "port.example.com", "StatusCode": "HTTP_301"}}'
  labels:
    app: example
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /yolo1
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /static/yolo2
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /*
        backend:
          serviceName: example-backend
          servicePort: 80
  - host: yelp.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: yelp-redirect
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: yelp-redirect-ssl
          servicePort: use-annotation
  - host: '*.example.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /yolo1
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /static/yolo2
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /*
        backend:
          serviceName: example-backend
          servicePort: 80
  - host: yelp.example.co.su
    http:
      paths:
      - path: /*
        backend:
          serviceName: yelp-redirect
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: yelp-redirect-ssl
          servicePort: use-annotation
  - host: example.me
    http:
      paths:
      - path: /
        backend:
          serviceName: exampleme-redirect-slash
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: exampleme-redirect-all
          servicePort: use-annotation
      - path: /
        backend:
          serviceName: exampleme-redirect-slash-ssl
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: exampleme-redirect-all-ssl
          servicePort: use-annotation
```

The only really obvious difference with your  spec I can notice is the following
```yaml
     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
```
Another thing that might be relevant is that I am using the `1.0-beta.7` and not the `1.0.0` version of controller, might this be the root of my problem?

**Comment by M00nF1sh** [comment]
@stafot 
Are you tring to achieve below effect? 
**http**://example.com to  **http**://another.example.com
and **https**://example.com to  **https**://another.example.com 
If so, there is currently no way to achieve the above effect, since we cannot specify action/backend per listener for now. 
All action/backend you specified will be applied to **all** listeners, except an special case that when you redirect from http to https with same domain/path, that redirect action is only applied to http listener, which is an trick to support http->https use case)

**Comment by stafot** [comment]
@M00nF1sh 
Sorry for my late response but I was on my Christmas vacations. No the effect I want to achieve is all to redirect to `https`

**Comment by M00nF1sh** [comment]
@stafot 
Hi, I believe your desired effect can be achieved by below:
The diffs from your version is 
1. removed all your **-ssl actions.
2. Changed protocol from HTTP to HTTPS in your redirect actions.
I guess you misunderstood the "Protocol/Host/Port" in "RedirectConfig", it's specify "where to redirect user to" instead of "whether to redirect for current request if matching the protocol/host/port".
By default, the redirect action will be applied to all protocol/port(all listeners).

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "example-alb-ing"
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80, "HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:283511030707:certificate/21e7282a-cede-42b4-a1be-b9811dde14a9
    alb.ingress.kubernetes.io/actions.exampleme-redirect-slash: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "80", "Host": "example.com", "Path":"/", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.exampleme-redirect-all: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "80", "Host": "example.com", "Path":"/person/#{path}", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.yelp-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "80", "Host": "port.example.com", "StatusCode": "HTTP_301"}}'
  labels:
    app: example
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /yolo1
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /static/yolo2
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /*
        backend:
          serviceName: example-backend
          servicePort: 80
  - host: yelp.example.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: yelp-redirect
          servicePort: use-annotation
  - host: '*.example.com'
    http:
      paths:
      - path: /
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /yolo1
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /static/yolo2
        backend:
          serviceName: example-frontend
          servicePort: 80
      - path: /*
        backend:
          serviceName: example-backend
          servicePort: 80
  - host: yelp.example.co.su
    http:
      paths:
      - path: /*
        backend:
          serviceName: yelp-redirect
          servicePort: use-annotation
  - host: example.me
    http:
      paths:
      - path: /
        backend:
          serviceName: exampleme-redirect-slash
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: exampleme-redirect-all
          servicePort: use-annotation
```

**Comment by stafot** [comment]
@M00nF1sh 
Thanks for your support. It almost worked the way you suggested. But I think there was a typo on your rules. 

```yaml
    alb.ingress.kubernetes.io/actions.exampleme-redirect-slash: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "example.com", "Path":"/", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.exampleme-redirect-all: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "example.com", "Path":"/person/#{path}", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.yelp-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "Host": "port.example.com", "StatusCode": "HTTP_301"}}'

```
The above syntax solve my problem and worked as expected.  

Again, appreciate all your effort to debug my issue.
