### ISSUE TITLE
ssl-redirect only when incoming port is 80 ?

### ISSUE THREAD

**Issue by gigi-at-zymergen** [kubernetes-sigs/aws-alb-ingress-controller#793]
I have a situation where I have 2 https listen-ports defined and I want ssl redirect to 443 when the incoming request is http:80 .

I have the following annotations:
```
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}, {"HTTPS": 8443} ]'
```
And the first rule is: 
```
  rules:
  - http:
      paths:
      - backend:
          serviceName: redirect
          servicePort: use-annotation
        path: /*
```
I do NOT want the redirect action when the incoming port is 8443, but it is currently being added to that listener. Is there a way I can modify the actions.redirect annotation to only add the redirect rule on the http:80 listener and not the https:8443 listener ?
