### ISSUE TITLE
Ingress > nginx resolver address?

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-alb-ingress-controller#795]
Not sure if it is the right place for this question. I am using NodePort service and nginx deployement to accept / from the ingress resource. And then I have the following nginx configuration to avoid using outdated IP address once the upstream services' IP address change:
```
    listen 80;
    access_log /var/log/nginx/app.access_log main;
    error_log /var/log/nginx/app.error_log;
    resolver 127.0.0.1 [::1]:5353 valid=10s;
    set $upstream http://svc-web;
    location / {
          proxy_pass $upstream;
          proxy_http_version 1.1;
     }
    }
```
Which IP address should be used in this case? Thanks. Reference: https://github.com/ubuntu/microk8s/issues/224

**Comment by M00nF1sh** [comment]
Hi, are you trying to using an nginx to accept traffic and proxy it to backend service running in k8s?
If so, i'd suggest to use [nginx ingress controller](https://kubernetes.github.io/ingress-nginx/), which manages the nginx configuration and deal with service ip changes for you automatically.

If your k8s stack running in aws, i'd suggest to use our project(alb ingress controller), which use AWS Application LoadBalancer(L7 loadbalancer) to accept traffic and proxy to backend services in k8s

**Comment by M00nF1sh** [comment]
close this issue since itself isnot related to this project 😄

**Comment by khteh** [comment]
Hi @M00nF1sh, yes I am using an nginx to accepte and forward traffic to upstream Headless Service with StatefulSets. No, I am not going to use the nginx ingress controller because it only manages to create Classic ELB. Yes, I am using your project ALB Ingress Controller. However, I am not using NodePort Service at the upstream to accept traffic. Instead, I need to use Headless Service with StatefulSets and that's why I use nginx to proxy the traffic to the upstreams and that's why I have this question and issue.

**Comment by M00nF1sh** [comment]
Hi, 
You should set to your DNS Server to the DNS of your cluster.
For my EKS based cluster(which uses kube-dns), i'm can use `resolver kube-dns.kube-system valid=10s;`

**Comment by M00nF1sh** [comment]
Another way is two use an sidecar of dns server on your nginx pod(that relies on local pod dns/search path), and you don't need to specify the dns server and can use the full dns name of your backend service. sample below
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: issue-795
  name: nginx-config
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      server { # php/fastcgi
        listen 80;
        resolver 127.0.0.1:53 ipv6=off valid=10s;
        set $upstream http://backend:8080;
        location / {
              proxy_pass $upstream;
              proxy_http_version 1.1;
         }
      }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: issue-795
  name: proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      - name: dnsmasq
        image: "janeczku/go-dnsmasq:release-1.0.7"
        args:
          - --listen
          - "127.0.0.1:53"
          - --default-resolver
          - --append-search-domains
          - --verbose
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: issue-795
  name: backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  clusterIP: None
  selector:
    app: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: issue-795
spec:
  serviceName: "backend"
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
```

**Comment by M00nF1sh** [comment]
In the meantime, why don't you create a normal NodePort service along with your Headless Service for your pods? The only benefit of nginx i can think of is it can do path rewrite for you 😄

**Comment by khteh** [comment]
Hi @M00nF1sh, can you tell me more about your last solution - create a normal NodePort? I know these 2 things are definitely needed:

(1) NodePort to proxy traffic - That's why I use NGinx and I can only think of NGinx.
(2) Headless Service - for my StatefulSets.

Thanks.

**Comment by M00nF1sh** [comment]
@khteh 
I mean like below
```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: issue-795
  name: backend
spec:
  ports:
  - port: 80
    targetPort: 8080
  clusterIP: None
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  namespace: issue-795
  name: backend-for-ingress
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
  selector:
    app: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: issue-795
spec:
  serviceName: "backend"
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
```
There are two services
1. a headless called`backend` for your statefulset if you need the dns behavior 😄 
1. a nodePort called `backend-for-ingress` for your statefulset, and use backend-for-ingress in your ingress definitions.
Then you can avoid the nginx setup 😄
