### ISSUE TITLE
Feature Request: Denote some ingress rules as externally/manually managed

### ISSUE THREAD

**Issue by gigi-at-zymergen** [kubernetes-sigs/aws-alb-ingress-controller#797]
We have a routing situation where we have legacy clients expecting to make calls of type `subdomain.domain.net/v1/endpoints`, and we are actively trying to decompose an old monolith. 

Some of those endpoints are now implemented as k8s microservices, and some of them are now implemented as AWS lambdas, as well as continuing to run the old monolith on EC2 instances. 

We currently have an ALB where we can manually configure target groups and path based rules to route to the Lambdas and the old ec2 nodes. We also have an ALB that was created by the alb ingress controller that can route traffic to the k8s microservices, but there is no easy way to unify these under one Route53 entry so the clients can continue to call `subdomain.domain.net/v1/endpoints` and have the proper path based rules applied.

I thought I might be able to hack it by creating an `externalName` service in k8s, and creating an ingress rule such as :
ExternalName
```
kind: Service
apiVersion: v1
metadata:
  name: external-name -service
  namespace: development
spec:
  type: ExternalName
  externalName: subdomain-monolith.example.com    
```
Ingress Rule
```
  - host: "subdomain.example.com"
    http:
      paths:
      - backend:
          serviceName: k8s-microservice
          servicePort: 80
        path: /v1/k8s-microservice-endpoint/*
  - host: "subdomain.example.com "
    http:
      paths:
      - backend:
          serviceName: external-name -service
        path: /*
```
But this creates an error on not having defined k8s endpoints.  

I thought about creating an explicit endpoints resource and associating a static ip with an NLB and sending traffic to the NLB and then to the lambdas/ec2, but we do SSL termination on the ALB for the Lambdas. 

It's starting to look like we'll have to advance our plans to use Envoy/Ambassador/Gloo or something similar as a more complex proxying layer. 

However, this would all be easy if there were a way to tell the ALB ingress controller that there are rules and target groups that will be externally managed and not to delete them.

I know this is not currently supported, ie https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/762 . But I wanted to submit a use case where this would come in super handy. Many organizations are in the midst of decomposing much larger legacy apps into microservices and serverless functions and we're probably not the only ones with this situation.

**Comment by M00nF1sh** [comment]
Hi,
How about extend our current [alb.ingress.kubernetes.io/actions.$action-name](https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/ingress/annotation/#actions) annotation

So for your case, you can manually create targetGroup for your backend, let's assume its ARN is `legacy-tg-arn`.
And then make your ingress looks like below:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: testcase
  name: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.legacy-app: '{"Type": "forward", "TargetGroupArn": "legacy-tg-arn"}'
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: legacy-app
              servicePort: use-annotation
          - path: /normal-path
            backend:
              serviceName: echoserver
              servicePort: 80
```

Should be easy to implement
