### ISSUE TITLE
Getting alb.ingress.kubernetes.io/certificate-arn  from a variable (secret)

### ISSUE THREAD

**Issue by omerfsen** [kubernetes-sigs/aws-alb-ingress-controller#800]
Currently we define to use SSL cert ARN like: 

```
alb.ingress.kubernetes.io/certificate-arn : arn:aws:acm:eu-central-1.......
````

It would be nice to get this value from a variable (from a secret) like:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-alb-ssl
type: Opaque
data:
  arn:  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

Then use it on alb.ingress.kubernetes.io/certificate-arn   like

```
alb.ingress.kubernetes.io/certificate-arn: $(aws-alb-ssl.arn)

````
