### ISSUE TITLE
Possibility to specify multtiple and different oidc/cognito auth actions for 1 service

### ISSUE THREAD

**Issue by JakubJecminek** [kubernetes-sigs/aws-alb-ingress-controller#831]
Hi,
great job with implementation of oidc/cognito auth actions. After reading through documentation I have question, if it is possible to specify multiple different auth actions for single service but with different host. For example if I have service serviceA which listens on *.myhost.com and I specify two rules for this service:

```
  - host: 'abc.myhost.com'
    http:
      paths:
      - backend:
          serviceName: serviceA
          servicePort: 80
        path: /*
  - host: 'def.myhost.com'
    http:
      paths:
      - backend:
          serviceName: serviceA
          servicePort: 80
        path: /*

```

I want abc.myhost.com have different auth oidc action(completely different oidc IDP) then def.myhost.com. 

Can it be done with current implementation somehow?
