### ISSUE TITLE
URL rewrite?

### ISSUE THREAD

**Issue by khteh** [kubernetes-sigs/aws-alb-ingress-controller#835]
Hi;

   I know you have mentioned to me before that "the only benefit of using NGINX is URL rewrite". I now bump into issue with an application not using TOMCAT web server. I deploy a kibana Service and StatefulSet and expose it through the ALB ingress and since there is no rewrite, the Kibana application process rejects the service request and returns 404. Any insight and advise is appreciated. Thanks.

https://stackoverflow.com/questions/54413885/kibana-deployed-to-kubernetes-cluster-returns-404

**Comment by khteh** [comment]
It works now after I add the following to the Kibana config:
```
    server.basePath: "/my-kibana"
    server.rewriteBasePath: true
```
And use `/my-kibana/api/status` as my Service healthcheck endpoint.

**Comment by M00nF1sh** [comment]
glad it worked 😄 .
I'll sync with ALB team to check whether support URL rewrite is on their road map.

**Comment by khteh** [comment]
Thanks. I think it makes sense as we don't expect every micro service is behind a web server / nginx. I am just lucky that Kibana has thought of this and provides this configurable solution but not not be lucky with other applications...;)

**Comment by khyew** [comment]
wait, is URL rewrite not available via this k8s controller, or is it not currently supported by the ALB product at all?

**Comment by M00nF1sh** [comment]
Hi, the URL rewrite is not supported by ALB itself, but support URL rewrite is on roadmap.

**Comment by khteh** [comment]
Any ETA? ;)

**Comment by AdeOpe** [comment]
I would love to get url rewrite.
it seems basically impossible to have grafana on a /grafana path in the ALB
even after setting the 
grafana.ini.server.root_url

i always get 

![image](https://user-images.githubusercontent.com/5416277/53109577-1005dc80-3531-11e9-8ca8-a1f00c775358.png)

**Comment by mtovmassian** [comment]
Any update for this _rewrite-target_ support?

**Comment by SankarGopal77** [comment]
I've been trying to redirect to RabbitMQ & Grafana using ALB ingress controller and it doesn't work if I specify path other then "/".  is it still not supported in ALB?

**Comment by M00nF1sh** [comment]
Hi, it's still not supported in ALB. And ALB team is working on solution for request manipulation like this.

**Comment by SaltedEggIndomee** [comment]
Any updates on this?? Seems like we have to use nginx for now because this feature/annotation is already implemented on nginx.

**Comment by wwwy3y3** [comment]
@nitrag Thanks. Exactly what I'm looking for!

**Comment by sarbajitdutta** [comment]
@nitrag I am trying to redirect to two different services based on path. But it does not work even with actions. 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: reciter-ing
  namespace: reciter
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/actions.swagger-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTP", "Port": "80", "Path": "/#{path}/swagger-ui.html", "Query": "#{query}", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.pubmed-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTP", "Port": "80", "Path": "/", "Query": "#{query}", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/actions.scopus-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTP", "Port": "80", "Path": "/scopus", "Query": "#{query}", "StatusCode": "HTTP_301"}}'
  labels:
    environment: dev
    owner: szd2013
spec:
  rules:
    - http:
        paths:
          # - path: /pubmed
          #   backend:
          #     serviceName: swagger-redirect
          #     servicePort: use-annotation
          - path: /*
            backend:
              serviceName: reciter-pubmed
              servicePort: 80
          - path: /pubmed/*
            backend:
              serviceName: pubmed-redirect
              servicePort: use-annotation
          # - path: /scopus
          #   backend:
          #     serviceName: swagger-redirect
          #     servicePort: use-annotation
          - path: /scopus/*
            backend:
              serviceName: scopus-redirect
              servicePort: use-annotation
          - path: /scopus/*
            backend:
              serviceName: reciter-scopus
              servicePort: 80

**Comment by ravimartins** [comment]
I need exactly @sarbajitdutta is trying to do. I have another service mapped to a path, but I can't rewrite based on it.

**Comment by pdeva** [comment]
without the rewrite feature, it makes path based routing useless in EKS. its surprising this issue has no priority at all and has been closed by the team.

**Comment by nperiwal** [comment]
Even the same issue has been faced by us, and many more will face this. This feature should be taken up on priority. It's not possible to configure every micro-services with a base path.

**Comment by aliharis** [comment]
Any ETA on this?

**Comment by NArnott** [comment]
+1 would love to see this supported.

**Comment by finnhvman** [comment]
We bumped into this issue today, we need this feature.

**Comment by rifelpet** [comment]
Requesting support for this here isn't productive because the ingress controller can't support URL rewrites until ALBs themselves do. It would be much more effective for everyone to go through their standard AWS support channels to request this functionality. Once ALBs support it, the ingress controller can be updated to support it as well.

**Comment by krishna1250** [comment]
This is needed we cant have multiple ingress controllers running, kubernetes is complex as it is.

/kind : feature
/severity: blocking.

**Comment by lkr2des** [comment]
Please have the URL rewrite feature available in ALB ingress

**Comment by M00nF1sh** [comment]
@lkr2des we cannot have it before ALB itself support it..

**Comment by rphipps** [comment]
@M00nF1sh can you explain what part of the ALB does not support the rewrites?  The AWS UI for load balancers seems to support it, Is there a part of the AWS API that does not support it?  Or some other part of the software in the stack?

Thanks.

**Comment by rraisal** [comment]
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-restheart-user-assets
  annotations:
    kubernetes.io/ingress.class: "nginx"
    enable-underscores-in-headers: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    **nginx.ingress.kubernetes.io/rewrite-target: /product/user_assets.files/$2**
spec:
  tls:
    - hosts:
      - XXXXXXXXX
      secretName: tls-secret
  rules:
  - host: XXXXXXXXXXXXX
    http:
      paths:
      **- path: /user_assets(/|$)(.*)**
        backend:
          serviceName: restheart-service
          servicePort: 8080

Is there any hack to serve my request like the above nginx ingress in EKS ALB ingress

**Comment by sbussard** [comment]
this is still very much a problem
/reopen

**Comment by schollii** [comment]
@nitrag I don't see how this will work: the redirect action will notify client to redirect to another URL which is not what is desired

**Comment by dhavaln** [comment]
Using EKS for a dry run and bumped into this issue.

**Comment by rraisal** [comment]
@dhavaln have look at https://github.com/kubernetes/ingress-nginx/issues/6292#issuecomment-763765042

**Comment by sidpremkumar** [comment]
+1 would love this feature!

**Comment by schollii** [comment]
An alternative to nginx-ingress that uses AWS LB controller, might work for some: 

Instead of rewriting
 https://yourdomain.com/service-name/path 

to 

http://service-name/path

setup instead to rewrite
 https://service-name.yourdomain.com/path 

to

http://service-name/path

This can be easily achieved by setting a group annotation on the ingress resources of your cluster, so they all use the same ALB, and a wildcard record in DNS / route53.

**Comment by nicolas-vivot** [comment]
@schollii with your solution you're just moving this problem to the client that will have to handle many sub domains depending on the service it has to call, instead of having just one and the the path determine the resource to request.

It's still fine for internal domains / sub domains, but for public ones, clients should never be aware of / have to care about your internal service organization.

**Comment by schollii** [comment]
@nicolas-vivot no, there are only 2 records to write, super easy: `yourdomain.com` and `*.yourdomain.com`, both cname to the ALB domain. So the client needs to know nothing about the subdomains/services just like they don't need to know anything about the paths that come after the domain in the URL.

**Comment by orona-yuca** [comment]
@nitrag using this way, the request will be redirected to the alb url in the `/` path, but what do you do when you want to access a different path than the `/`? I imagine that the service could have many paths, and we want to access it using the main path that we set on ingress

**Comment by igoratencompass** [comment]
Why is this closed? What's the go with the support for the `ingress.kubernetes.io/rewrite-target` annotation?

**Comment by WilliamsDL** [comment]
Agreed with igoratencompass...  Why is this closed?  What is the solution?

**Comment by raresserban** [comment]
Also bumped into this issue. I guess I can modify my Nginx config to strip the path, but it should be supported natively...

**Comment by rudian** [comment]
Surprised that the cloud provider with the largest market share in the world does not have this feature, very disappointed...... meaningless to use EKS 👎

**Comment by edgarkz** [comment]
Any ETA please on rewrite feature?

**Comment by HarrisonTotty** [comment]
Also commenting to show the need for this feature.

**Comment by DariusX** [comment]
As mentioned earlier in this thread, this controller is limited to features available in AWS Load Balancer.
So, AWS would need to support rewrite in their Load Balancer.
Onlt then would this Controller be able to configure the Load Balancer to use such a feature

**Comment by khteh** [comment]
Do Azure and GCP have this feature in their load balancer?

**Comment by CatfoodHeist** [comment]
This is a deal breaker and I cannot use this controller in any of my solutions. I would rather not have to install other controllers to handle such a simple feature.

**Comment by schollii** [comment]
@CatfoodHeist the main problem IIUC is that AWS ALB itself does not support that. The ALB controller is just the mechanism to instantiate ALB, so the Ingress is ultimately limited by the cloud implementation, AWS ALB in this case. 

There are a couple of workarounds that do not involve another controller: 

1. Use subdomains instead of paths: this will not work in all situations, but has worked very well for me in some systems. Basically you install aws-lb-controller and instead of your endpoints being of the form https://your.domain/path-1, path-2 etc, you configure the Ingress so ALB will dispatch https://path-1.your.domain/... to http://service-1/..., https://path-2.your.domain/... to http://service-2/..., etc. 
2. Use a classic load balancer (the default created by k8s when using straight LoadBalancer type Service): this does not require any controller, not even aws-lb-controller, but does require you deploy a "router" eg nginx, in your cluster; then configure nginx pod to do the dispatching to different services (via a config map).

**Comment by ShubhamRasal** [comment]
bumped into this requirement. 
My requirement was to redirect traffic coming / to /app. 
Used alb redirect annotation for it.
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#:~:text=alb.ingress.kubernetes.io/actions.%24%7Baction-name%7D%20Provides%20a%20method%20for%20configuring%20custom%20actions%20on%20a%20listener%2C%20such%20as%20Redirect%20Actions.
`    annotations: 
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /app/loginForm.do
      alb.ingress.kubernetes.io/healthcheck-port: "8080"
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/success-codes: 200-300
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/actions.redirect-to-app: >
        {"type":"redirect","redirectConfig":{ "host": "#{host}","port": "#{port}","protocol": "#{protocol}","query": "#{query}","path":"/instahms/loginForm.do","statusCode":"HTTP_302"}} 
    rules:
      - host: myapp.example.com
        http: 
          paths:
            - path: /app
              pathType: Prefix
              backend:
                service:
                  name: "app-service"
                  port: 
                    number: 8080
            - path: /
              pathType: Exact
              backend:
                service:
                  name: redirect-to-app
                  port: 
                    name: use-annotation
instaWorker:
`

**Comment by eocern** [comment]
Well my problem is like many others that I want to have 
/app1 ->container-app1
/app2 ->container-app2
and I want to rewrite/ignore the passing of the "/app1" or "/app2" path to the container.

I guess we just need to vote and monitor https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1571 as posted earlier on here.
or did somebody in the meantime found a solution for that specific case and ALB controller ?

**Comment by schollii** [comment]
I use subdomains instead:

app1.domain1/... -> container-app1/... 
app2.domain2/... -> container-app2/... 

Works like a charm.

**Comment by ilvez** [comment]
> I use subdomains instead:
> 
> app1.domain1/... -> container-app1/... app2.domain2/... -> container-app2/...
> 
> Works like a charm.

I'm currently trying to dig out how to make it work. Can you share configuration how to achieve this?

**Comment by ilvez** [comment]
> I use subdomains instead:
> 
> app1.domain1/... -> container-app1/... app2.domain2/... -> container-app2/...
> 
> Works like a charm.

Thanks for tip. For others who are stumbling upon how to achieve it. Below's the example, but main pieces of glue were correct `alb.ingress.kubernetes.io/conditions` annotations and actually `pathType: Prefix` with `path: /`.
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: services
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: 'instance'
    alb.ingress.kubernetes.io/certificate-arn: XXX
    external-dns.alpha.kubernetes.io/hostname: 'service1.example.com,service2.example.com'
    alb.ingress.kubernetes.io/conditions.service1: >
      [{"field":"host-header","hostHeaderConfig":{"values":["service1.example.com"]}}]
    alb.ingress.kubernetes.io/conditions.service2: >
      [{"field":"host-header","hostHeaderConfig":{"values":["service2.example.com"]}}]
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service1
              port:
                number: 5000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service2
              port:
                number: 8080

```

Crucial part was to have `service1` and `service2` health check annotation in Service's as well, if default `/` does not respond for example:
```
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    app.kubernetes.io/name: service1
    app.kubernetes.io/instance: service1
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
```

**Comment by MBingazy** [comment]
Thank you @oliver-sentianse, in this way I have to create an endpoint `(service.a.b.c)` for each service I have, also I have to add actions for each service in the ingress resource yaml

**Comment by MBingazy** [comment]
@oliver-sentianse Could you elaborate more? How did you add the annotations, and how did you redirect?

**Comment by chelto** [comment]
I've been struggling for days on this now. All of the AWS blogs and example using ALB controller and path routing are the same and don't actually work with real world services like Graphana.
@schollii method works for me and i'll use this.

**Comment by td-harness** [comment]
This is asinine that ALB does not support a simple rewrite op that has been around for decades, for this reason alone we will not support alb or encourage use of EKS

**Comment by Ar11rA** [comment]
Is there any way to rewrite as of now?

**Comment by csgitharness** [comment]
Yes, inquiring minds would like to know the same @Ar11rA above just asked, I still find it hard to believe this is continually swept under the rug with all the requests for enhancement over the years.

**Comment by td-harness** [comment]
Yes, inquiring minds would like to know the same @Ar11rA above just asked, I still find it hard to believe this is continually swept under the rug with all the requests for enhancement over the years.

**Comment by td-harness** [comment]
I see the workarounds proposed here but this requires complete redesign with what I would at least, consider a hack around subdomain routing instead of path based

**Comment by td-harness** [comment]
This would require a 'complete re-design' on our part as well that you and others mentioned previously, and to fit a few edge cases likely not going to happen.. I didn't expect much but hey I tried, even as far as reaching out to old colleagues at AWS that are PMs.  If all of our customers utilized AWS this would be a no brainer on the workaround (or just use transport level appliance, nlb, etc).  Surprised this doesn't support this ootb, oh well :)

**Comment by MrSunny-M** [comment]
Only solution is to find an alternative to ALB ingress controller now.

**Comment by franramvel** [comment]
Bump, the aws team sold us ALB as the perfect soultion for this type of scenarios, so, after a months of development, when we tried to deploy our solution we got stuck for this reason.... now whe have to search a workaround for a such simple task

**Comment by schollii** [comment]
@franramvel

You pretty much have 2 choices: nginx controller and the solution I discuss in several places in this thread. The latter may or may not be applicable to your specifics but it's not just theoretical, it's a proven solution that is very easy to implement once you understand the wildcard DNS record. Here are links to the relevant comments: 

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/835#issuecomment-819087649

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/835#issuecomment-1017924317

https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/835#issuecomment-1404017761 

Hth!

**Comment by franramvel** [comment]
@schollii thank you! I Just implemented it yesterday with the subdomain workaround, fortunately we got DNS as requierement so that save us.

Also, I think Nginx is a perfect workaround when there is no DNS, so I'll check it for future implementations where we can't get use of DNS

**Comment by hughesadam87** [comment]
It is very frustrating coming in in 2023 and seeing suggestions to switch to nginx controller.  

Our use case is we have no domain, we just have microservices and want to route simply to 

   /service1
   /service2
   /service3

The ALB creates an a-record so there's no domain to subdomain to.  This feels like the most basic use case for an ingress controller, almost like running a `print` statement in a coding language, only to find out printing isn't supported...

**Comment by hughesadam87** [comment]
For what it's worth, here is how to deploy nginx as a reverse proxy.  We can't use DNS subdomains for various reasons, so this is super heavy handed.  I tried the route others suggested of just using nginx-ingress-controller, but for the life of me couldn't get it to provision ALBs correctly - it kept creating class load balancers.

# deployment-nginx.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      # ConfigMap is where the actual routing is defined
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config

```

service-nginx.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

```

relevant-ingress (assume you have two services named "foo" and "bar")
```
spec:
  ingressClassName: "alb"
  rules:
    - http:
        paths:
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: nginx-reverse-proxy
                port:
                  number: 80
          - path: /bar
            pathType: Prefix
            backend:
              service:
                name: nginx-reverse-proxy
                port:
                  number: 80
```

And finally, the nginx settings in file "configmap-nginx.yaml"

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;

            location /foo {
                rewrite ^/foo/(.*) /$1 break;
                proxy_pass http://foo;
            }

            location /bar {
                rewrite ^/bar/(.*) /$1 break;
                proxy_pass http://bar;
            }
        }
    }

```
