### ISSUE TITLE
Target group not created for HTTPS only ingress

### ISSUE THREAD

**Issue by NickSchleicher** [kubernetes-sigs/aws-alb-ingress-controller#837]
Version: 1.1.1

If I create my ingress that is HTTPS only, no target group is created (logs are showing no signs of `DescribeTargetGroup/CreateTargetGroup` api calls

Ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nifi
  namespace: ar
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:iam::X:server-certificate/ardevcanary
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: sg-X, sg-X, sg-X
    alb.ingress.kubernetes.io/subnets: subnet-X, subnet-X
    alb.ingress.kubernetes.io/success-codes: 200,302
    alb.ingress.kubernetes.io/tags: Environment={{ .Values.environment }}
spec:
  rules:
    - https:
        paths:
          - path: /
            backend:
              serviceName: nifi
              servicePort: 8443
```

However, if I change the `https` rule  to `http`, the Target Group is created

I'm not sure if this is a bug or my ingress definition is missing annotations or setup wrong
