### ISSUE TITLE
Get client real ip alb-ingress > ingress-nginx > app

### ISSUE THREAD

**Issue by sysbes** [kubernetes-sigs/aws-alb-ingress-controller#841]
Hello, i have alb-ingress-controller to serve as the first hop, plus nginx-ingress-controller for final routing. 
How i can get real client ip in nginx logs and in app. Now i see only internal node's ip in ingress-nginx logs and in my app. 

**My alb-ingress:**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "rootalb"
  namespace: ingress-nginx
  labels:
    app: "rootalb"
  annotations:
    # trigger the alb-ingress-controller
    kubernetes.io/ingress.class: "alb"

    # set ALB parameters
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "instance"
    alb.ingress.kubernetes.io/subnets: xxx,xxx,xxx
    alb.ingress.kubernetes.io/certificate-arn: xxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-group-attributes: 
    stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60

    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200,404"

spec:
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: "ingress-nginx"
          servicePort: 80
```

**My app - ingess-nginx config**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prom
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/whitelist-source-range: x.x.x.x/x
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      real_ip_header X-Forwarded-For;
      set_real_ip_from 0.0.0.0/0;
spec:
  rules:
  - host: app1.domain.com
    http:
      paths:
      - backend:
          serviceName: app1
          servicePort: 3000
  - host: app2.domain.com
    http:
      paths:
      - backend:
          serviceName: app2
          servicePort: 9090
  - host: app3.domain.com
    http:
      paths:
      - backend:
          serviceName: app3
          servicePort: 9093
```

For example setup i'm use this article - https://medium.com/@dmaas/amazon-eks-ingress-guide-8ec2ec940a70
