### ISSUE TITLE
Controller fails with i/o timeout on elasticloadbalancing endpoint in us-west-2

### ISSUE THREAD

**Issue by jwsomis** [kubernetes-sigs/aws-alb-ingress-controller#854]
First time trying to get this set up and getting an i/o timeout error on the regions elb endpoint.
In the alb-ingress-controller.yaml I have only set the cluster name. Everything else is the defaults.
My ingress.yaml looks like:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  namespace: project
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-#####,subnet-#####,subnet-#####
    alb.ingress.kubernetes.io/tags: Environment=stage,Team=test
spec:
  rules:
    - host: test.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: test
              servicePort: 80
```
And when I apply the files I get the error:
```
kubebuilder/controller "msg"="Reconciler error" "error"="failed to find existing LoadBalancer due to RequestError: send request failed\ncaused by: Post https://elasticloadbalancing.us-west-2.amazonaws.com/: dial tcp: i/o timeout"  "controller"="alb-ingress-controller" "request"={"Namespace":"project","Name":"test"}
```

I am able to reach that endpoint from the container host, but am lost as to what else to do to debug this.
