### ISSUE TITLE
ALB ingress controller doesn't respond to ingress manifests with cognito settings

### ISSUE THREAD

**Issue by procyclinsur** [kubernetes-sigs/aws-alb-ingress-controller#871]
## Overview
I am honestly not sure whether this is a bug or my own mistake..  That being said, I have followed the documents and instructions [here](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/822) about fixing iam issues.

Kubernetes: v1.13.3
alb-ingress-controller: v1.1.1 (was on v1.1.0 first then upgraded)

Please let me know if any additional information is required.

### Main Issue
- Unable to deploy Cognito Enabled Deployment.

#### Sub-Issue 1
- On fresh deploy, alb-ingress-controller does not parse the template as configured by then end of the [Cognito Authentication Enabled Deployment](#cognito) section.

There is no output on the logs console whatsoever from my alb-ingress-controller, almost like there is no recognition that a manifest has been sent.

#### Sub-Issue 2
- On an update of an existing deployment as configured by [SSL Deployment](#ssl) to the configuration described by [Cognito Authentication Enabled Deployment](#cognito), the alb-ingress-controller throws the following error.
    - ```E0225 12:21:29.307783       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to  reconcile listeners due to failed to build listener config due to annotation alb.ingress.kubernetes.io/certificate-arn must be specified for https listener"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"testapp.iot-sys.net"}```

The problem with the above error is that `alb.ingress.kubernetes.io/certificate-arn` is indeed defined, and works as described below.

## Environment
I started my deployment small and worked up to try to eliminate issues as much as possible.  My initial deployment looked similar to the below document.

### Application
test-service.yml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: testapp
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp
spec:
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: procyclinsur/log-http-headers:latest
        name: testapp
        ports:
        - containerPort: 80
          name: http
```

### Initial Ingress Deployment 
test-ingress.yml
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testapp.iot-sys.net
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=test,Owner=Scott
spec:
  rules:
    - host: testapp.iot-sys.net
      http:
        paths:
          - path: /
            backend:
              serviceName: testapp
              servicePort: 80
```

This sets up an http load balancer as expected on AWS.  

### <a name="ssl"></a>SSL Deployment

I then set up SSL/HTTPS redirect by adding the following annotations.

- Added to `metadata->annotations`:
```yaml
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:ap-northeast-1:xxxxxxxx:certificate/xxxxxxxx'
```
- Added as first item to `spec->rules->http->paths`:
```yaml
- path: /*
  backend:
    serviceName: ssl-redirect
    servicePort: use-annotation
```

The end result was successful HTTPS connections to the end server. (although redirects didn't work.. issue for another time).

### <a name="cognito"></a>Cognito Authentication Enabled Deployment
With HTTPS working correctly (mostly) I wanted to move onto Cognito authentication.  To enable Cognito authentication I added the below to my file.

- Added to `metadata->annotations`:
```yaml
alb.ingress.kubernetes.io/auth-type: cognito
alb.ingress.kubernetes.io/auth-scope: openid
alb.ingress.kubernetes.io/auth-session-timeout: 3600
alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:ap-northeast-1:xxxxxxxx:userpool/ap-northeast-1_pa9vj7sbL","UserPoolClientId":"xxxxxxxx","UserPoolDomain":"iot-sys"}'
```

The results:  Please see [Issues](#issues)
