### ISSUE TITLE
Fallback automatic certificate assignment not working

### ISSUE THREAD

**Issue by echoboomer** [kubernetes-sigs/aws-alb-ingress-controller#896]
Based on this PR:
https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/851

I would expect to be able to pass in this configuration for an ingress and have certificate assignment work using wildcards, provided there is an ACM cert that matches:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-app
  labels:
    app: test-app
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/security-groups: sg-name
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-2017-01
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=604800,deregistration_delay.timeout_seconds=0
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - http:
      paths:
        - path: /*
          backend:
            serviceName: test-app
            servicePort: 443
  tls:
  - hosts:
    - test-app.foobar.com
```

In this case, a wildcard certificate for `*.foobar.com` exists. However, when a Helm release is pushed using this configuration (no certificate annotation, with the inclusion of the `spec.tls.hosts` section), the controller logs present these errors:

```bash
E0314 17:56:38.698337       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to build listener config due to missing certificates annotation alb.ingress.kubernetes.io/certificate-arn could not find any matching certificates from ACM to auto-load"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"test-app"}
```

Here is the version information. We are using the official chart but specifying the latest release tag:

```bash
-------------------------------------------------------------------------------
AWS ALB Ingress controller
  Release:    v1.1.1
  Build:      git-87bef3eb
  Repository: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
-------------------------------------------------------------------------------
```
