### ISSUE TITLE
Helm ignores Cognito, fails silently

### ISSUE THREAD

**Issue by crawforde** [kubernetes-sigs/aws-alb-ingress-controller#897]
I followed the setup [instructions](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/guide/cognito/setup.md) and then the [example](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/master/docs/examples/cognito-ingress-template.yaml) helm template specified in this repo for setting up a Cognito authentication listener for my application load balancer. Helm completely ignores it. External dns and everything else works properly, route53 is updated properly, and the application loads, but no authentication is required. The Cognito listener is not applied to the load balancer, and there are no logs in the load balancer indicating that k8s even attempted to create it.

My ingress template is the following:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <lb-name>
  namespace: <namespace-name>
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /ping/
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=<stage>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-session-timeout: '3600'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn": "arn:aws:cognito-idp:<region>:<account-id>:userpool/<region><cognito-id>", "UserPoolClientId": "<user-pool-client-id>", "UserPoolDomain": "<user-pool-authentication-domain-prefix>"}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:<region>:<account-id>:certificate/<cert-id>
spec:
  rules:
    - host: <app>.<stage>.<company>.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              # Configured via the redirect settings in the annotations
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: <service-name>
              servicePort: <service-port>
```
Is there something I'm missing here? No changes that I make even get k8s to acknowledge the auth annotations.
