### ISSUE TITLE
How to use multiple Certificates for multiple domains

### ISSUE THREAD

**Issue by bingochen87** [kubernetes-sigs/aws-alb-ingress-controller#907]
ingress.yml
```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-southeast-1:074210164173:certificate/80ecdaf5-eba8-46a4-b64a-d8ab8433e937,arn:aws:acm:ap-southeast-1:074210164173:certificate/702d8514-c993-4cab-b798-d47c1a89b2b0"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200,404"
  labels:
    app: hyperion-alb-ingress
spec:
  rules:
    - host: api.hyn.space
      http:
        paths:
          - path: /
            backend:
              serviceName: dmapper-server
              servicePort: 80
    - host: myservice.tile.map3.network
      http:
        paths:
          - path: /
            backend:
              serviceName: myservice
              servicePort: 80
```
apply this yml file, when I watch ingress logs, I get:
I0402 03:44:19.869086       1 targetgroup.go:119] default/ingress: creating target group 620b3d26-d00f8636ccb5f120cce
I0402 03:44:20.162366       1 targetgroup.go:138] default/ingress: target group 620b3d26-d00f8636ccb5f120cce created: arn:aws:elasticloadbalancing:ap-southeast-1:074210164173:targetgroup/620b3d26-d00f8636ccb5f120cce/310154b60e461104
I0402 03:44:20.196031       1 tags.go:43] default/ingress: modifying tags {  kubernetes.io/ingress-name: "ingress",  kubernetes.io/service-name: "myservice",  kubernetes.io/service-port: "80",  kubernetes.io/cluster/hyperion-cluster: "owned",  kubernetes.io/namespace: "default"} on arn:aws:elasticloadbalancing:ap-southeast-1:074210164173:targetgroup/620b3d26-d00f8636ccb5f120cce/310154b60e461104
I0402 03:44:20.260337       1 targets.go:73] default/ingress: Adding targets to arn:aws:elasticloadbalancing:ap-southeast-1:074210164173:targetgroup/620b3d26-d00f8636ccb5f120cce/310154b60e461104: i-00bda7fea22bad42a:31093, i-0899b76590c0253a6:31093
I0402 03:44:20.535620       1 rules.go:60] default/ingress: creating rule 2 on arn:aws:elasticloadbalancing:ap-southeast-1:074210164173:listener/app/620b3d26-default-ingress-e8c7/fb7530957957c3c4/b365c2bd65c1cb4a
I0402 03:44:20.564557       1 rules.go:77] default/ingress: rule 2 created with conditions [{    Field: "host-header",    Values: ["myservice.tile.map3.network"]  },{    Field: "path-pattern",    Values: ["/"]  }]
I0402 03:44:20.564689       1 listener.go:100] default/ingress: modifying listener 443, arn: arn:aws:elasticloadbalancing:ap-southeast-1:074210164173:listener/app/620b3d26-default-ingress-e8c7/fb7530957957c3c4/e5f1168031ff826f
E0402 03:44:20.617832       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile listener due to CertificateNotFound: Certificate 'arn:aws:acm:ap-southeast-1:074210164173:certificate/80ecdaf5-eba8-46a4-b64a-d8ab8433e937,arn:aws:acm:ap-southeast-1:074210164173:certificate/702d8514-c993-4cab-b798-d47c1a89b2b0' not found\n\tstatus code: 400, request id: 9937c72d-54f9-11e9-b8ac-55e9b4cb99c4"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"ingress"}
I0402 03:44:22.008618       1 listener.go:100] default/ingress: modifying listener 443, arn: arn:aws:elasticloadbalancing:ap-southeast-1:074210164173:listener/app/620b3d26-default-ingress-e8c7/fb7530957957c3c4/e5f1168031ff826f
E0402 03:44:22.051112       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile listener due to CertificateNotFound: Certificate 'arn:aws:acm:ap-southeast-1:074210164173:certificate/80ecdaf5-eba8-46a4-b64a-d8ab8433e937,arn:aws:acm:ap-southeast-1:074210164173:certificate/702d8514-c993-4cab-b798-d47c1a89b2b0' not found\n\tstatus code: 400, request id: 9a146b43-54f9-11e9-b5bf-ad11ff5d8e8d"  "controller"="alb-ingress-controller" "request"={"Namespace":"default","Name":"ingress"}

I can confirm both Certificate file is exists in my AWS ACM.

**Comment by rifelpet** [comment]
What version of the aws-alb-ingress-controller are you running?

**Comment by bingochen87** [comment]
> What version of the aws-alb-ingress-controller are you running?

```yml
# Application Load Balancer (ALB) Ingress Controller Deployment Manifest.
# This manifest details sensible defaults for deploying an ALB Ingress Controller.
# GitHub: https://github.com/kubernetes-sigs/aws-alb-ingress-controller
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alb-ingress-controller
  name: alb-ingress-controller
  # Namespace the ALB Ingress Controller should run in. Does not impact which
  # namespaces it's able to resolve ingress resource for. For limiting ingress
  # namespace scope, see --watch-namespace.
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alb-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alb-ingress-controller
    spec:
      containers:
        - args:
            # Limit the namespace where this ALB Ingress Controller deployment will
            # resolve ingress resources. If left commented, all namespaces are used.
            # - --watch-namespace=your-k8s-namespace

            # Setting the ingress-class flag below ensures that only ingress resources with the
            # annotation kubernetes.io/ingress.class: "alb" are respected by the controller. You may
            # choose any class you'd like for this controller to respect.
            - --ingress-class=alb

            # Name of your cluster. Used when naming resources created
            # by the ALB Ingress Controller, providing distinction between
            # clusters.
            - --cluster-name=hyperion-cluster

            # AWS VPC ID this ingress controller will use to create AWS resources.
            # If unspecified, it will be discovered from ec2metadata.
            # - --aws-vpc-id=vpc-xxxxxx
            # AWS region this ingress controller will operate in.
            # If unspecified, it will be discovered from ec2metadata.
            # List of regions: http://docs.aws.amazon.com/general/latest/gr/rande.html#vpc_region
            # - --aws-region=us-west-1
            # Enables logging on all outbound requests sent to the AWS API.
            # If logging is desired, set to true.
            # - ---aws-api-debug
            # Maximum number of times to retry the aws calls.
            # defaults to 10.
            # - --aws-max-retries=10
          env:
            # AWS key id for authenticating with the AWS API.
            # This is only here for examples. It's recommended you instead use
            # a project like kube2iam for granting access.
            #- name: AWS_ACCESS_KEY_ID
            #  value: KEYVALUE
            # AWS key secret for authenticating with the AWS API.
            # This is only here for examples. It's recommended you instead use
            # a project like kube2iam for granting access.
            #- name: AWS_SECRET_ACCESS_KEY
            #  value: SECRETVALUE
          # Repository location of the ALB Ingress Controller.
          image: docker.io/amazon/aws-alb-ingress-controller:v1.1.0
          imagePullPolicy: Always
          name: server
          resources: {}
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: alb-ingress
      serviceAccount: alb-ingress
```
