### ISSUE TITLE
How to set multiple host use same serviceName

### ISSUE THREAD

**Issue by bingochen87** [kubernetes-sigs/aws-alb-ingress-controller#908]
As I say, `How to set multiple host use same serviceName`
I have a separate service that needs to bind multiple hosts. How do I set it up in ingress's configuration file? Can be to set up multiple `- host`?

**Comment by M00nF1sh** [comment]
Hi, you can use multiple host in ingress specification
like
```
spec:
  rules:
    - host: host1.example.com
       http:
        paths:
          - path: /path
            backend:
              serviceName: echoserver
              servicePort: 80
    - host: host2.example.com
       http:
        paths:
          - path: /path
            backend:
              serviceName: echoserver
              servicePort: 80
```

**Comment by bingochen87** [comment]
```yml
spec:
  rules:
    - host: host1.example.com
       http:
        paths:
          - path: /path
            backend:
              serviceName: echoserver
              servicePort: 80
    - host: host2.example.com
       http:
        paths:
          - path: /path
            backend:
              serviceName: echoserver
              servicePort: 80
```
That's how I set it up right now.

I was wondering if I could:
```yml
spec:
  rules:
    - host: host1.example.com
    - host: host2.example.com
       http:
        paths:
          - path: /path
            backend:
              serviceName: echoserver
              servicePort: 80
```
or
```yml
spec:
  rules:
    - host: host1.example.com, host2.example.com
       http:
        paths:
          - path: /path
            backend:
              serviceName: echoserver
              servicePort: 80
```

**Comment by M00nF1sh** [comment]
Hi, both alternative you posted won't work :D
You can referer the kubernetes spec for Ingress here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#ingressrule-v1beta1-extensions

**Comment by bingochen87** [comment]
Thank you for your reply.

**Comment by ramondeklein** [comment]
Because Kubernetes uses straight YAML, I would think you could make use of YAML anchors:
```
spec:
  rules:
    - host: host1.example.com
       http: &backend
        paths:
          - path: /path
            backend:
              serviceName: echoserver
              servicePort: 80
    - host: host2.example.com
       http: *backend
```
