### ISSUE TITLE
Service annotation not taking priority over ingress annotation

### ISSUE THREAD

**Issue by darrylb-github** [kubernetes-sigs/aws-alb-ingress-controller#910]
Hi,

In the docs it says:

> Annotations applied to service have higher priority over annotations applied to ingress

I'm trying to set the target type for one of my service rules to instance instead of IP. Example:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: test-service
  annotations:
    alb.ingress.kubernetes.io/target-type: instance
spec:
  type: NodePort
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: us-east-1d-internal-subnet,us-east-1c-internal-subnet,=us-east-1e-internal-subnet
    alb.ingress.kubernetes.io/security-groups: eks-alb-internal-sg-useast1-devel-02
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:12345678:certificate/1234...
    alb.ingress.kubernetes.io/tags: Environment=devel
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
  labels:
    app: test
spec:
  rules:
    - host: test.example.com
      http:
        paths:
          - backend:
              serviceName: "test-service"
              servicePort: 80
```

In this scenario I expect the service target type annotation `alb.ingress.kubernetes.io/target-type: instance` to take precedence over the `alb.ingress.kubernetes.io/target-type: ip` annotation in the ingress.

Instead the ALB target group gets created with target type ip.

Is this a bug or am I doing something wrong? 🤔 

```
Release:    v1.1.2
  Build:      git-cc1c5971
```

Thanks,
Darryl

**Comment by darrylb-github** [comment]
Note my example only has one rule on the ingress, and if this was all I needed I could just remove the ingress annotation or set it to instance there, but in reality I have ingresses with multiple rules where I want to only apply the instance target-type selectively to some of the rules.

**Comment by darrylb-github** [comment]
The same issue applies using the 2048 game example:

```
apiVersion: v1
kind: Namespace
metadata:
  name: "2048-game"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "2048-deployment"
  namespace: "2048-game"
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: "2048"
    spec:
      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: "2048"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: "service-2048"
  namespace: "2048-game"
  annotations:
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "2048"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "2048-ingress"
  namespace: "2048-game"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: 2048-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "service-2048"
              servicePort: 80

```
