### ISSUE TITLE
Ingress controller not working as expected

### ISSUE THREAD

**Issue by praveenkadimi** [kubernetes-sigs/aws-alb-ingress-controller#919]
I have an API service which is working as expected when I use path as "/". but when I mention path as "/test" which is not working site not reachable. Is the issue related to ingress or clusterIP?

**Comment by rverma-nikiai** [comment]
You need to use path as /*

**Comment by praveenkadimi** [comment]
This is still not working paths /test/*, it is working only with /. Please help me with this

**Comment by rverma-nikiai** [comment]
You need to add path in ingress as /*. This should reflect in your alb rule as 
Host :x.y.z
Path: /*

**Comment by M00nF1sh** [comment]
Hi, 
did you application accepts traffic at /test/*?  ALB don't support path-rewrite now, so the HTTP request send to your backend will be same as the request to ALB (/test/* in your case).

**Comment by praveenkadimi** [comment]
I have 2 API services which we wants go as below paths 
1. /api1/
2./api2/
but its not working with above paths it is working with path as "/"

**Comment by vickyshah129** [comment]
Did anyone get a chance to resolve it? i am using AKS (ingress controllers) and facing the same issue. My application has no context path. When i use `/` in the path, it works fine, but when i use even single character with slash, it doesn't route to anything. Can anyone see into this matter. Any help would be appreciated.

**Comment by bigkraig** [comment]
> Did anyone get a chance to resolve it? i am using minikube locally (ingress controllers) and facing the same issue. My application has no context path. When i use `/` in the path, it works fine, but when i use even single character with slash, it doesn't route to anything. Can anyone see into this matter. Any help would be appreciated.

what do you have as your path rule? it should be `Path: /*`, it sounds like it could be `Path: /`

**Comment by praveenkadimi** [comment]
Please use below lines to solve the issue 
Annotations:
"nginx.ingress.kubernetes.io/rewrite-target": "/$1",

"paths": [
            {
              "backend": {
                "serviceName": "projectsetupservice",
                "servicePort": 80
              },
              "path": "/?(.*)"
            },
            {
              "backend": {
                "serviceName": "storagesetupservice",
                "servicePort": 80
              },
              "path": "/storagesetup/?(.*)"
            }
              ]

**Comment by vickyshah129** [comment]
> Please use below lines to solve the issue
> Annotations:
> "nginx.ingress.kubernetes.io/rewrite-target": "/$1",
> 
> "paths": [
> {
> "backend": {
> "serviceName": "projectsetupservice",
> "servicePort": 80
> },
> "path": "/?(._)" }, { "backend": { "serviceName": "storagesetupservice", "servicePort": 80 }, "path": "/storagesetup/?(._)"
> }
> ]

I used this before and nothing changed. It works for one path but not for other. Almost ends up in the same behavior.

**Comment by praveenkadimi** [comment]
Share your ingress file

**Comment by vickyshah129** [comment]
i have tried all variations.

**1-** With straight paths as described in official kubernetes ingress controller setup tutorial.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: hello-world.info
   http:
     paths:
     - backend:
         serviceName: order
         servicePort: 8080
       path: /
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v1/
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v2/
```

In above configuration, only path with **/** routes fine. All other shows spring boot's **Whitelabel Error Page**

2- When i follow the above $1 notion, all three routes (including even simple slash) shows **Whitelabel Error Page**. Example config below:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 - host: hello-world.info
   http:
     paths:
     - backend:
         serviceName: order
         servicePort: 8080
       path: /?(.)
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v1/?(.)
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v2/?(.)
```

Kindly correct me if there is a configuration issue or anything i can change. Thanks

**Comment by vickyshah129** [comment]
> > Did anyone get a chance to resolve it? i am using minikube locally (ingress controllers) and facing the same issue. My application has no context path. When i use `/` in the path, it works fine, but when i use even single character with slash, it doesn't route to anything. Can anyone see into this matter. Any help would be appreciated.
> 
> what do you have as your path rule? it should be `Path: /*`, it sounds like it could be `Path: /`

for me, **/*** and **/** doing the same, no change.

**Comment by vickyshah129** [comment]
> Share your ingress file

 i have tried all variations.

**1-** With straight paths as described in official kubernetes ingress controller setup tutorial.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: hello-world.info
   http:
     paths:
     - backend:
         serviceName: order
         servicePort: 8080
       path: /
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v1/
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v2/
```

In above configuration, only path with **/** routes fine. All other shows spring boot's **Whitelabel Error Page**

2- When i follow the above $1 notion, all three routes (including even simple slash) shows **Whitelabel Error Page**. Example config below:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 - host: hello-world.info
   http:
     paths:
     - backend:
         serviceName: order
         servicePort: 8080
       path: /?(.)
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v1/?(.)
     - backend:
         serviceName: order
         servicePort: 8080
       path: /v2/?(.)
```

Kindly correct me if there is a configuration issue or anything i can change. Thanks
