### ISSUE TITLE
https paths not being created?

### ISSUE THREAD

**Issue by JoshuaEdwards1991** [kubernetes-sigs/aws-alb-ingress-controller#922]
Hi,

When I run this Ingress, only http paths are created. Any ideas why the https paths aren't being created on the alb? The target group is being created.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "eks-aws-alb-ingress-controller-ingress"
  labels:
    app: "eks-aws-alb-ingress-controller-ingress-app"
  annotations:
    # trigger the alb-ingress-controller
    kubernetes.io/ingress.class: "alb"
    # set ALB parameters
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "instance"
    alb.ingress.kubernetes.io/security-groups: ${SEC_GROUP}
    alb.ingress.kubernetes.io/subnets: ${PUB_SUB_1}, ${PUB_SUB_2}, ${PUB_SUB_3}
    alb.ingress.kubernetes.io/certificate-arn: ${ALB_CERT}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    # allow 404s on the health check
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/success-codes: "200,404"
spec:
  # forward all requests to nginx-ingress-controller
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - path: /*
        backend:
          serviceName: "eks-nginx-ingress-controller"
          servicePort: 80
```
