### ISSUE TITLE
1.1.2 bug, and cognito problems

### ISSUE THREAD

**Issue by travis-webb** [kubernetes-sigs/aws-alb-ingress-controller#928]
Here is a cleaned up version of my `ingress.yaml`
```
---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: appname-ingress
  namespace: appname
  labels:
    app: appname
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0842,subnet-0c00
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxxxxxxx:certificate/abcdefg-hijk-lmno-pqrs-tuvxyz
    alb.ingress.kubernetes.io/security-groups: sg-04ff,sg-0a23,sg-0ed5
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: appname-service
              servicePort: 8000
```
First, a bug:
Upgrading ingress controller from 1.1.0 to 1.1.2 causes it to always use only the 'default' vpc security group when creating my load balancer and not use any of the security groups I have listed in the `security-groups` annotation. 

Second, I cannot get Cognito authentication to work at all (using 1.1.0). 
```
    alb.ingress.kubernetes.io/auth-type: cognito
    alb.ingress.kubernetes.io/auth-scope: openid
    alb.ingress.kubernetes.io/auth-idp-cognito: '{"UserPoolArn":"arn:aws:cognito-idp:us-east-1:xxxxxxxxxx:userpool/us-east-1_abcdefghij", "UserPoolClientId":"abcclientidxxxxxyz", "UserPoolDomain":"cognito-login"}'
    alb.ingress.kubernetes.io/auth-session-cookie: AWSELBAuthSessionCookie
    alb.ingress.kubernetes.io/auth-session-timeout: '86400'
    alb.ingress.kubernetes.io/auth-on-unauthenticated-request: authenticate
```
Adding these annotations to the annotations section in the `ingress.yaml` file above ...
1. Causes my security groups annotation to be ignored and only the default security group to be used (just like when upgrading from 1.1.0 to 1.1.2).
2. For some reason causes my listener on 443 to be disabled even though the listener + redirect on 80 is still there (and redirecting to the one at 443 which doesn't exist). Also, because it doesn't exist, there is no cognito config to even look at.
