### ISSUE TITLE
NoCredentialProviders: no valid providers in chain when using with kube2iam

### ISSUE THREAD

**Issue by artemmikhalitsin** [kubernetes-sigs/aws-alb-ingress-controller#929]
The following is my deployment yaml, as generated by helm

```
# Source: aws-alb-ingress-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-alb-ingress-controller
  labels:
    app.kubernetes.io/name: aws-alb-ingress-controller
    helm.sh/chart: aws-alb-ingress-controller-0.1.7
    app.kubernetes.io/instance: aws-alb-ingress-controller
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: aws-alb-ingress-controller
      app.kubernetes.io/instance: aws-alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aws-alb-ingress-controller
        app.kubernetes.io/instance: aws-alb-ingress-controller
      annotations:
        iam.amazonaws.com/role: alb-ingress-controller

    spec:
      containers:
        - name: aws-alb-ingress-controller
          image: "docker.io/amazon/aws-alb-ingress-controller:v1.1.2"
          imagePullPolicy: IfNotPresent
          args:
            - --cluster-name=api-main
            - --ingress-class=alb

          env:
          ports:
            - name: health
              containerPort: 10254
              protocol: TCP
          resources:
            {}

      serviceAccountName: aws-alb-ingress-controller
      terminationGracePeriodSeconds: 60
```

As you can see, I've added the proper pod annotation, containing the role name, as listed in my aws account. Additionally, I have tested that kube2iam assigns the correct role to the pods by launching this same deployment with a busybox-curl image, and running `curl 169.254.169.254/latest/meta-data/iam/security-credentials/`, which returns `alb-ingress-controller`

However, when I create an Ingress resource, I get the following error in the logs of the controller deployment:

```
E0423 16:59:57.675574       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to build LoadBalancer configuration due to failed to get AWS tags. Error: NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"  "controller"="alb-ingress-controller" "request"={"Namespace":"echoserver","Name":"echoserver"}
```

Below is an example of an ingress I am launching:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: echoserver
  namespace: echoserver
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
    - host: echoserver.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: echoserver
              servicePort: 80
```
