### ISSUE TITLE
How to troubleshoot ALB not appearing for subdomain

### ISSUE THREAD

**Issue by seenickcode** [kubernetes-sigs/aws-alb-ingress-controller#932]
Hello, I've gotten my ALB to work in the past using the following config and the domain domain.com, yet when I create the ALB for a subdomain, such as foobar.domain.com, I can't see my ALB created in AWS. 

Note that I've created my cluster using kops with RBAC enabled:
```
kops create cluster --zones us-east-1a,us-east-1b,us-east-1c,us-east-1e --node-size t2.micro --node-count 2 --node-volume-size 15 --master-size t2.micro --authorization RBAC --node-size t2.micro --master-size t2.micro --master-count 1 --master-volume-size 15 --ssh-public-key ~/.ssh/id_rsa.pub <MY CLUSTER NAME> --yes
```

Here's my config:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fcc
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:redacted:certificate/redacted"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - host: foobar.domain.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: fcc
              servicePort: 80
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: alb-ingress-controller
  name: alb-ingress-controller
rules:
  - apiGroups:
      - ""
      - extensions
    resources:
      - configmaps
      - endpoints
      - events
      - ingresses
      - ingresses/status
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - patch
  - apiGroups:
      - ""
      - extensions
    resources:
      - nodes
      - pods
      - secrets
      - services
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: alb-ingress-controller
  name: alb-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alb-ingress-controller
subjects:
  - kind: ServiceAccount
    name: alb-ingress
    namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: alb-ingress-controller
  name: alb-ingress
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alb-ingress-controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alb-ingress-controller
    spec:
      containers: 
        - image: docker.io/amazon/aws-alb-ingress-controller:v1.1.0
          imagePullPolicy: Always
          args:
            - --ingress-class=alb
            - --cluster-name=<MY CLUSTER CREATED BY KOPS>
          name: server
          resources: {}
          terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: alb-ingress
      serviceAccount: alb-ingress
---
apiVersion: v1
kind: Service
# ... my service ...
---
apiVersion: apps/v1
kind: Deployment
# ... my deployment ...
```

Here's my Ingress description:
```
kubectl describe ing/fcc
Name:             fcc
Namespace:        default
Address:          
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                     Path  Backends
  ----                     ----  --------
  staging.seenickcode.com  
                           /*   ssl-redirect:use-annotation (<none>)
                           /*   fcc:80 (100.96.1.5:8888,100.96.2.3:8888)
Annotations:
  alb.ingress.kubernetes.io/actions.ssl-redirect:    {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
  alb.ingress.kubernetes.io/certificate-arn:         arn:aws:acm:us-east-1:redacted:certificate/redacted
  alb.ingress.kubernetes.io/listen-ports:            [{"HTTP": 80}, {"HTTPS":443}]
  alb.ingress.kubernetes.io/scheme:                  internet-facing
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/actions.ssl-redirect":"{\"Type\": \"redirect\", \"RedirectConfig\": { \"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}","alb.ingress.kubernetes.io/certificate-arn":"arn:aws:acm:us-east-1:redacted:certificate/reacted","alb.ingress.kubernetes.io/listen-ports":"[{\"HTTP\": 80}, {\"HTTPS\":443}]","alb.ingress.kubernetes.io/scheme":"internet-facing","kubernetes.io/ingress.class":"alb"},"name":"fcc","namespace":"default"},"spec":{"rules":[{"host":"foobar.domain.com","http":{"paths":[{"backend":{"serviceName":"ssl-redirect","servicePort":"use-annotation"},"path":"/*"},{"backend":{"serviceName":"fcc","servicePort":80},"path":"/*"}]}}]}}

  kubernetes.io/ingress.class:  alb
Events:                         <none>
```

So the issues is that my ALB isn't appearing in AWS. (this config worked in the past btw, but not when I was using a subdomain. What is the recommended way to troubleshoot this?
