### ISSUE TITLE
K8S Network policy applied is not allowing traffic

### ISSUE THREAD

**Issue by scrumteamwhitewalkers** [kubernetes-sigs/aws-alb-ingress-controller#973]
We are using ALB ingress controller for creating load balancers.  Now, our requirement is that, pods should be able to receive calls from only within the namespace and from loadbalancer.  But, we are not able to configure ALB with a network policy.

ALB is deployed in 'kube-system', and our pod is deployed in a namespace 'one'.  

Our Network policy looks like this: 

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: one
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          test-label: kube-system
```

The pods are now unreachable from the load balancer.

Is this configuration even possible from ALB?

**Comment by aalimovs** [comment]
@scrumteamwhitewalkers did you get anywhere with this?

**Comment by aalimovs** [comment]
whoever stumbles upon this, we achieved this on EKS with [Calico](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) with the following:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-from-other-namespaces
  namespace: your-namespace
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-external
  namespace: your-namespace
spec:
  podSelector:
    matchLabels:
      app: your-app-label
  ingress:
  - from: []
    ports:
    - port: 3000
```

The first policy denies traffic from other namespaces. However, if you're using alb-ingress-controller with `alb.ingress.kubernetes.io/target-type: instance` (default), this will break your services, because of NodePort. To solve that, allow ingress to your app port in the second policy.

While you've restricted pod to pod traffic, the pods in other namespaces can still hit the service via `node-ip:port`. This is good enough for our setup, since these services are exposed to the public via ALB anyway.

If you want to restrict even that, look at denying all egress in all namespaces and only whitelisting the ones the require. The other solution is to change `alb.ingress.kubernetes.io/target-type` to `ip`, however, you'll introduce downtime to your deployments, see #814 for more details.
