### ISSUE TITLE
Options to use regex like nginx use-regex

### ISSUE THREAD

**Issue by TiloGit** [kubernetes-sigs/aws-alb-ingress-controller#992]
on AKS I use nginx **use-regex** what are my options with AWS EKS ALB? 

here my yaml file for ngnix on Azure
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dummy-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - dummy.westus2.cloudapp.azure.com
    secretName: tls-secret
  rules:
  - host: dummy.westus2.cloudapp.azure.com
    http:
      paths:
      - path: /oneoneone.*
        backend:
           serviceName: ecm-1-svc
           servicePort: 9443
      - path: /twotwotwo.*
        backend:
          serviceName: ecm-2-svc
          servicePort: 9443
      - path: /threethreethree
        backend:
          serviceName: ecm-3-svc
          servicePort: 9443
      - path: /fourfourfour.*
        backend:
          serviceName: ecm-4-svc
          servicePort: 9443
```
