### ISSUE TITLE
Annotations not read - failed to reconcile listeners

### ISSUE THREAD

**Issue by RuBiCK** [kubernetes-sigs/aws-alb-ingress-controller#994]
I want to make the following redirects using actions in annotations:

1)80 -> 443
2)domain.com:443 -> www.domain.com:443

SSL redirect works fine but when I add the second redirect using actions, I get the following error:

```
E0809 09:31:00.876448       1 :0] kubebuilder/controller "msg"="Reconciler error" "error"="failed to reconcile listeners due to failed to reconcile rules due to backend with `servicePort: use-annotation` was configured with `serviceName: www-redirect` but an action annotation for www-redirect is not set"  "controller"="alb-ingress-controller" "request"={"Namespace":"marketplace-pre","Name":"pre-marketplace--front"}
```

ingress.yaml

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pre-marketplace--front
  labels:
    app.kubernetes.io/name: marketplace-frontend
    helm.sh/chart: marketplace-v0.1.0
    app.kubernetes.io/instance: pre-frontend
    app.kubernetes.io/managed-by: Tiller
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:842754592251:certificate/4dfa56d7-292f-4552-bf2e-419exxxxxxx
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-041d3dffcc01xxxxx,subnet-068df0fccba8xxxxx,subnet-0ce06ff4bd60xxxxx
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/web-acl-id: 447b201b-442b-4d49-8892-xxxxxx
    alb.ingrtes.kubernetes.io/actions.www-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Host": "www.#{host}", "Query": "#{query}", "Path": "/#{path}",
      "Port": "443", "StatusCode": "HTTP_301" }}'
    kubernetes.io/ingress.class: alb-pre
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: "pre.midomain.es"
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
    - host: "pre.midomain.es"
      http:
        paths:
          - path: /*
            backend:
              serviceName: www-redirect
              servicePort: use-annotation
    - host: "www.pre.midomain.es"
      http:
        paths:
          - path: /*
            backend:
              serviceName: marketplace-pre-frontend
              servicePort: 3000
```

If you take a look to the deployed yaml, it contains `antions.www-redirect` but the error shows that annotation doesn't exist

Is there anything I'm doing wrong or it's a bug?

`ALB ingress contoller: v1.1.2`
